import typing
import pydantic
import pydantic_xml

# This file was automatically generated by relaxng-to-pydantic. Do not modify.
class uuid(pydantic_xml.BaseXmlModel, tag='uuid', search_mode='unordered'):
	value: typing.Union[typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{32}')], typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{8}\\-([a-fA-F0-9]{4}\\-){3}[a-fA-F0-9]{12}')]]

_uuid = uuid

class hostcpu_arch(pydantic_xml.BaseXmlModel, tag='arch', search_mode='unordered'):
	value: typing.Literal['aarch64', 'alpha', 'armv6l', 'armv7l', 'cris', 'i686', 'ia64', 'lm32', 'loongarch64', 'm68k', 'microblaze', 'microblazeel', 'mips', 'mipsel', 'mips64', 'mips64el', 'openrisc', 'parisc', 'parisc64', 'ppc', 'ppc64', 'ppc64le', 'ppcemb', 'riscv32', 'riscv64', 's390', 's390x', 'sh4', 'sh4eb', 'sparc', 'sparc64', 'unicore32', 'x86_64', 'xtensa', 'xtensaeb']

_hostcpu_arch = hostcpu_arch

class pae(pydantic_xml.BaseXmlModel, tag='pae', search_mode='strict'):
	pass

_pae = pae

class nonpae(pydantic_xml.BaseXmlModel, tag='nonpae', search_mode='strict'):
	pass

_nonpae = nonpae

class vmx(pydantic_xml.BaseXmlModel, tag='vmx', search_mode='strict'):
	pass

_vmx = vmx

class svm(pydantic_xml.BaseXmlModel, tag='svm', search_mode='strict'):
	pass

_svm = svm

class hostcpu_features(pydantic_xml.BaseXmlModel, tag='features', search_mode='strict'):
	pae: typing.Optional[_pae] = pydantic_xml.element(tag='pae', default=None)
	nonpae: typing.Optional[_nonpae] = pydantic_xml.element(tag='nonpae', default=None)
	vmx: typing.Optional[_vmx] = pydantic_xml.element(tag='vmx', default=None)
	svm: typing.Optional[_svm] = pydantic_xml.element(tag='svm', default=None)

_hostcpu_features = hostcpu_features

class model(pydantic_xml.BaseXmlModel, tag='model', search_mode='strict'):
	value: str

_model = model

class vendor(pydantic_xml.BaseXmlModel, tag='vendor', search_mode='strict'):
	value: str

_vendor = vendor

class microcode(pydantic_xml.BaseXmlModel, tag='microcode', search_mode='strict'):
	version: int = pydantic_xml.attr(name='version')

_microcode = microcode

class signature(pydantic_xml.BaseXmlModel, tag='signature', search_mode='strict'):
	family: int = pydantic_xml.attr(name='family')
	model: int = pydantic_xml.attr(name='model')
	stepping: int = pydantic_xml.attr(name='stepping')

_signature = signature

class counter(pydantic_xml.BaseXmlModel, tag='counter', search_mode='strict'):
	name: str = pydantic_xml.attr(name='name')
	frequency: int = pydantic_xml.attr(name='frequency')
	scaling: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='scaling')

_counter = counter

class cpu_topology(pydantic_xml.BaseXmlModel, tag='topology', search_mode='strict'):
	sockets: int = pydantic_xml.attr(name='sockets')
	dies: typing.Optional[int] = pydantic_xml.attr(name='dies', default=None)
	clusters: typing.Optional[int] = pydantic_xml.attr(name='clusters', default=None)
	cores: int = pydantic_xml.attr(name='cores')
	threads: int = pydantic_xml.attr(name='threads')

_cpu_topology = cpu_topology

class cpu_max_phys_addr(pydantic_xml.BaseXmlModel, tag='maxphysaddr', search_mode='strict'):
	mode: typing.Literal['emulate', 'passthrough'] = pydantic_xml.attr(name='mode')
	bits: typing.Optional[int] = pydantic_xml.attr(name='bits', default=None)
	limit: typing.Optional[int] = pydantic_xml.attr(name='limit', default=None)

_cpu_max_phys_addr = cpu_max_phys_addr

class hostcpu_feature(pydantic_xml.BaseXmlModel, tag='feature', search_mode='strict'):
	name: typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9\\-_]+')] = pydantic_xml.attr(name='name')

_hostcpu_feature = hostcpu_feature

class pages(pydantic_xml.BaseXmlModel, tag='pages', search_mode='strict'):
	unit: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='([bB]([yY][tT][eE][sS]?)?)|([kKmMgGtTpPeE]([iI]?[bB])?)')]] = pydantic_xml.attr(name='unit', default=None)
	size: int = pydantic_xml.attr(name='size')

_pages = pages

class hostcpu(pydantic_xml.BaseXmlModel, tag='cpu', search_mode='unordered'):
	arch: _hostcpu_arch = pydantic_xml.element(tag='arch')
	features: typing.Optional[_hostcpu_features] = pydantic_xml.element(tag='features', default=None)
	model: typing.Optional[_model] = pydantic_xml.element(tag='model', default=None)
	vendor: typing.Optional[_vendor] = pydantic_xml.element(tag='vendor', default=None)
	microcode: typing.Optional[_microcode] = pydantic_xml.element(tag='microcode', default=None)
	signature: typing.Optional[_signature] = pydantic_xml.element(tag='signature', default=None)
	counter: typing.Optional[_counter] = pydantic_xml.element(tag='counter', default=None)
	topology: typing.Optional[_cpu_topology] = pydantic_xml.element(tag='topology', default=None)
	maxphysaddr: typing.Optional[_cpu_max_phys_addr] = pydantic_xml.element(tag='maxphysaddr', default=None)
	feature_list: typing.Optional[typing.List[_hostcpu_feature]] = pydantic_xml.element(tag='feature', default=None)
	pages_list: typing.Optional[typing.List[_pages]] = pydantic_xml.element(tag='pages', default=None)

_hostcpu = hostcpu

class suspend_mem(pydantic_xml.BaseXmlModel, tag='suspend_mem', search_mode='strict'):
	pass

_suspend_mem = suspend_mem

class suspend_disk(pydantic_xml.BaseXmlModel, tag='suspend_disk', search_mode='strict'):
	pass

_suspend_disk = suspend_disk

class suspend_hybrid(pydantic_xml.BaseXmlModel, tag='suspend_hybrid', search_mode='strict'):
	pass

_suspend_hybrid = suspend_hybrid

class power_management(pydantic_xml.BaseXmlModel, tag='power_management', search_mode='unordered'):
	suspend_mem: typing.Optional[_suspend_mem] = pydantic_xml.element(tag='suspend_mem', default=None)
	suspend_disk: typing.Optional[_suspend_disk] = pydantic_xml.element(tag='suspend_disk', default=None)
	suspend_hybrid: typing.Optional[_suspend_hybrid] = pydantic_xml.element(tag='suspend_hybrid', default=None)

_power_management = power_management

class iommu_support(pydantic_xml.BaseXmlModel, tag='iommu', search_mode='strict'):
	support: typing.Optional[typing.Literal['yes', 'no']] = pydantic_xml.attr(name='support', default=None)

_iommu_support = iommu_support

class live(pydantic_xml.BaseXmlModel, tag='live', search_mode='strict'):
	pass

_live = live

class uri_transport(pydantic_xml.BaseXmlModel, tag='uri_transport', search_mode='unordered'):
	value: typing.Literal['vpxmigr', 'tcp', 'rdma', 'vzmigr']

_uri_transport = uri_transport

class uri_transports(pydantic_xml.BaseXmlModel, tag='uri_transports', search_mode='unordered'):
	uri_transport_list: typing.List[_uri_transport] = pydantic_xml.element(tag='uri_transport', min_length=1)

_uri_transports = uri_transports

class migration(pydantic_xml.BaseXmlModel, tag='migration_features', search_mode='strict'):
	live: typing.Optional[_live] = pydantic_xml.element(tag='live', default=None)
	uri_transports: typing.Optional[_uri_transports] = pydantic_xml.element(tag='uri_transports', default=None)

_migration = migration

class memory(pydantic_xml.BaseXmlModel, tag='memory', search_mode='strict'):
	value: int
	unit: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='([bB]([yY][tT][eE][sS]?)?)|([kKmMgGtTpPeE]([iI]?[bB])?)')]] = pydantic_xml.attr(name='unit', default=None)

_memory = memory

class pages_numa(pydantic_xml.BaseXmlModel, tag='pages', search_mode='strict'):
	value: int
	unit: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='([bB]([yY][tT][eE][sS]?)?)|([kKmMgGtTpPeE]([iI]?[bB])?)')]] = pydantic_xml.attr(name='unit', default=None)
	size: int = pydantic_xml.attr(name='size')

_pages_numa = pages_numa

class numa_distance(pydantic_xml.BaseXmlModel, tag='sibling', search_mode='strict'):
	id: int = pydantic_xml.attr(name='id')
	value: int = pydantic_xml.attr(name='value')

_numa_distance = numa_distance

class distances(pydantic_xml.BaseXmlModel, tag='distances', search_mode='unordered'):
	sibling_list: typing.List[_numa_distance] = pydantic_xml.element(tag='sibling', min_length=1)

_distances = distances

class size(pydantic_xml.BaseXmlModel, tag='size', search_mode='strict'):
	value: int = pydantic_xml.attr(name='value')
	unit: typing.Annotated[str, pydantic.Field(pattern='([bB]([yY][tT][eE][sS]?)?)|([kKmMgGtTpPeE]([iI]?[bB])?)')] = pydantic_xml.attr(name='unit')

_size = size

class line(pydantic_xml.BaseXmlModel, tag='line', search_mode='strict'):
	value: int = pydantic_xml.attr(name='value')
	unit: typing.Annotated[str, pydantic.Field(pattern='([bB]([yY][tT][eE][sS]?)?)|([kKmMgGtTpPeE]([iI]?[bB])?)')] = pydantic_xml.attr(name='unit')

_line = line

class numa_cache(pydantic_xml.BaseXmlModel, tag='cache', search_mode='unordered'):
	level: int = pydantic_xml.attr(name='level')
	associativity: typing.Literal['none', 'direct', 'full'] = pydantic_xml.attr(name='associativity')
	policy: typing.Literal['none', 'writeback', 'writethrough'] = pydantic_xml.attr(name='policy')
	size: _size = pydantic_xml.element(tag='size')
	line: _line = pydantic_xml.element(tag='line')

_numa_cache = numa_cache

class cpu(pydantic_xml.BaseXmlModel, tag='cpu', search_mode='strict'):
	id: int = pydantic_xml.attr(name='id')
	socket_id: typing.Optional[int] = pydantic_xml.attr(name='socket_id', default=None)
	die_id: typing.Optional[int] = pydantic_xml.attr(name='die_id', default=None)
	cluster_id: typing.Optional[int] = pydantic_xml.attr(name='cluster_id', default=None)
	core_id: typing.Optional[int] = pydantic_xml.attr(name='core_id', default=None)
	siblings: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='([0-9]+(-[0-9]+)?|\\^[0-9]+)(,([0-9]+(-[0-9]+)?|\\^[0-9]+))*')]] = pydantic_xml.attr(name='siblings', default=None)

_cpu = cpu

class cpus(pydantic_xml.BaseXmlModel, tag='cpus', search_mode='unordered'):
	num: int = pydantic_xml.attr(name='num')
	cpu_list: typing.Optional[typing.List[_cpu]] = pydantic_xml.element(tag='cpu', default=None)

_cpus = cpus

class cell(pydantic_xml.BaseXmlModel, tag='cell', search_mode='unordered'):
	id: int = pydantic_xml.attr(name='id')
	memory: typing.Optional[_memory] = pydantic_xml.element(tag='memory', default=None)
	pages_list: typing.Optional[typing.List[_pages_numa]] = pydantic_xml.element(tag='pages', default=None)
	distances: typing.Optional[_distances] = pydantic_xml.element(tag='distances', default=None)
	cache_list: typing.Optional[typing.List[_numa_cache]] = pydantic_xml.element(tag='cache', default=None)
	cpus: typing.Optional[_cpus] = pydantic_xml.element(tag='cpus', default=None)

_cell = cell

class cells(pydantic_xml.BaseXmlModel, tag='cells', search_mode='unordered'):
	num: int = pydantic_xml.attr(name='num')
	cell_list: typing.List[_cell] = pydantic_xml.element(tag='cell', min_length=1)

_cells = cells

class latency(pydantic_xml.BaseXmlModel, tag='latency', search_mode='strict'):
	initiator: int = pydantic_xml.attr(name='initiator')
	target: int = pydantic_xml.attr(name='target')
	cache: typing.Optional[int] = pydantic_xml.attr(name='cache', default=None)
	type: typing.Literal['access', 'read', 'write'] = pydantic_xml.attr(name='type')
	value: int = pydantic_xml.attr(name='value')

_latency = latency

class bandwidth(pydantic_xml.BaseXmlModel, tag='bandwidth', search_mode='strict'):
	initiator: int = pydantic_xml.attr(name='initiator')
	target: int = pydantic_xml.attr(name='target')
	cache: typing.Optional[int] = pydantic_xml.attr(name='cache', default=None)
	type: typing.Literal['access', 'read', 'write'] = pydantic_xml.attr(name='type')
	value: int = pydantic_xml.attr(name='value')
	unit: typing.Annotated[str, pydantic.Field(pattern='([bB]([yY][tT][eE][sS]?)?)|([kKmMgGtTpPeE]([iI]?[bB])?)')] = pydantic_xml.attr(name='unit')

_bandwidth = bandwidth

class numa_interconnects(pydantic_xml.BaseXmlModel, tag='interconnects', search_mode='unordered'):
	latency_list: typing.Optional[typing.List[_latency]] = pydantic_xml.element(tag='latency', default=None)
	bandwidth_list: typing.Optional[typing.List[_bandwidth]] = pydantic_xml.element(tag='bandwidth', default=None)

_numa_interconnects = numa_interconnects

class topology(pydantic_xml.BaseXmlModel, tag='topology', search_mode='strict'):
	cells: _cells = pydantic_xml.element(tag='cells')
	interconnects: typing.Optional[_numa_interconnects] = pydantic_xml.element(tag='interconnects', default=None)

_topology = topology

class bank_control(pydantic_xml.BaseXmlModel, tag='control', search_mode='strict'):
	granularity: int = pydantic_xml.attr(name='granularity')
	min: typing.Optional[int] = pydantic_xml.attr(name='min', default=None)
	unit: typing.Annotated[str, pydantic.Field(pattern='([bB]([yY][tT][eE][sS]?)?)|([kKmMgGtTpPeE]([iI]?[bB])?)')] = pydantic_xml.attr(name='unit')
	type: typing.Literal['both', 'code', 'data'] = pydantic_xml.attr(name='type')
	max_allocs: int = pydantic_xml.attr(name='maxAllocs')

_bank_control = bank_control

class bank(pydantic_xml.BaseXmlModel, tag='bank', search_mode='unordered'):
	id: int = pydantic_xml.attr(name='id')
	level: int = pydantic_xml.attr(name='level')
	type: typing.Literal['both', 'code', 'data'] = pydantic_xml.attr(name='type')
	size: int = pydantic_xml.attr(name='size')
	unit: typing.Annotated[str, pydantic.Field(pattern='([bB]([yY][tT][eE][sS]?)?)|([kKmMgGtTpPeE]([iI]?[bB])?)')] = pydantic_xml.attr(name='unit')
	cpus: typing.Annotated[str, pydantic.Field(pattern='([0-9]+(-[0-9]+)?|\\^[0-9]+)(,([0-9]+(-[0-9]+)?|\\^[0-9]+))*')] = pydantic_xml.attr(name='cpus')
	control_list: typing.Optional[typing.List[_bank_control]] = pydantic_xml.element(tag='control', default=None)

_bank = bank

class cpu_monitor_feature(pydantic_xml.BaseXmlModel, tag='feature', search_mode='strict'):
	name: typing.Annotated[str, pydantic.Field(pattern='(llc_|mbm_)[a-zA-Z0-9\\-_]+')] = pydantic_xml.attr(name='name')

_cpu_monitor_feature = cpu_monitor_feature

class cpu_monitor(pydantic_xml.BaseXmlModel, tag='monitor', search_mode='unordered'):
	level: typing.Optional[int] = pydantic_xml.attr(name='level', default=None)
	reuse_threshold: typing.Optional[int] = pydantic_xml.attr(name='reuseThreshold', default=None)
	max_monitors: int = pydantic_xml.attr(name='maxMonitors')
	feature_list: typing.List[_cpu_monitor_feature] = pydantic_xml.element(tag='feature', min_length=1)

_cpu_monitor = cpu_monitor

class cache(pydantic_xml.BaseXmlModel, tag='cache', search_mode='unordered'):
	bank_list: typing.List[_bank] = pydantic_xml.element(tag='bank', min_length=1)
	monitor: typing.Optional[_cpu_monitor] = pydantic_xml.element(tag='monitor', default=None)

_cache = cache

class node_control(pydantic_xml.BaseXmlModel, tag='control', search_mode='strict'):
	granularity: int = pydantic_xml.attr(name='granularity')
	min: typing.Optional[int] = pydantic_xml.attr(name='min', default=None)
	max_allocs: int = pydantic_xml.attr(name='maxAllocs')

_node_control = node_control

class node(pydantic_xml.BaseXmlModel, tag='node', search_mode='unordered'):
	id: int = pydantic_xml.attr(name='id')
	cpus: typing.Annotated[str, pydantic.Field(pattern='([0-9]+(-[0-9]+)?|\\^[0-9]+)(,([0-9]+(-[0-9]+)?|\\^[0-9]+))*')] = pydantic_xml.attr(name='cpus')
	control_list: typing.Optional[typing.List[_node_control]] = pydantic_xml.element(tag='control', default=None)

_node = node

class memory_bandwidth(pydantic_xml.BaseXmlModel, tag='memory_bandwidth', search_mode='unordered'):
	node_list: typing.List[_node] = pydantic_xml.element(tag='node', min_length=1)
	monitor: typing.Optional[_cpu_monitor] = pydantic_xml.element(tag='monitor', default=None)

_memory_bandwidth = memory_bandwidth

class doi(pydantic_xml.BaseXmlModel, tag='doi', search_mode='strict'):
	value: str

_doi = doi

class baselabel(pydantic_xml.BaseXmlModel, tag='baselabel', search_mode='strict'):
	value: str
	type: str = pydantic_xml.attr(name='type')

_baselabel = baselabel

class secmodel(pydantic_xml.BaseXmlModel, tag='secmodel', search_mode='unordered'):
	model: _model = pydantic_xml.element(tag='model')
	doi: _doi = pydantic_xml.element(tag='doi')
	baselabel_list: typing.Optional[typing.List[_baselabel]] = pydantic_xml.element(tag='baselabel', default=None)

_secmodel = secmodel

class hostcaps(pydantic_xml.BaseXmlModel, tag='host', search_mode='unordered'):
	uuid: typing.Optional[_uuid] = pydantic_xml.element(tag='uuid', default=None)
	cpu: _hostcpu = pydantic_xml.element(tag='cpu')
	power_management: typing.Optional[_power_management] = pydantic_xml.element(tag='power_management', default=None)
	iommu: typing.Optional[_iommu_support] = pydantic_xml.element(tag='iommu', default=None)
	migration_features: typing.Optional[_migration] = pydantic_xml.element(tag='migration_features', default=None)
	topology: typing.Optional[_topology] = pydantic_xml.element(tag='topology', default=None)
	cache: typing.Optional[_cache] = pydantic_xml.element(tag='cache', default=None)
	memory_bandwidth: typing.Optional[_memory_bandwidth] = pydantic_xml.element(tag='memory_bandwidth', default=None)
	secmodel_list: typing.Optional[typing.List[_secmodel]] = pydantic_xml.element(tag='secmodel', default=None)

_hostcaps = hostcaps

class ostype(pydantic_xml.BaseXmlModel, tag='os_type', search_mode='unordered'):
	value: typing.Literal['xen', 'linux', 'hvm', 'exe', 'uml']

_ostype = ostype

class wordsize(pydantic_xml.BaseXmlModel, tag='wordsize', search_mode='unordered'):
	value: typing.Literal['31', '32', '64']

_wordsize = wordsize

class emulator(pydantic_xml.BaseXmlModel, tag='emulator', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='(/|[a-zA-Z]:\\\\).+')]

_emulator = emulator

class loader(pydantic_xml.BaseXmlModel, tag='loader', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='(/|[a-zA-Z]:\\\\).+')]

_loader = loader

class machine(pydantic_xml.BaseXmlModel, tag='machine', search_mode='strict'):
	value: str
	canonical: typing.Optional[str] = pydantic_xml.attr(name='canonical', default=None)
	max_cpus: typing.Optional[int] = pydantic_xml.attr(name='maxCpus', default=None)
	deprecated: typing.Optional[typing.Literal['yes', 'no']] = pydantic_xml.attr(name='deprecated', default=None)

_machine = machine

class domain(pydantic_xml.BaseXmlModel, tag='domain', search_mode='unordered'):
	type: typing.Literal['qemu', 'kqemu', 'kvm', 'xen', 'lxc', 'uml', 'openvz', 'test', 'vmware', 'hyperv', 'vbox', 'phyp', 'vz', 'bhyve', 'hvf'] = pydantic_xml.attr(name='type')
	emulator: typing.Optional[_emulator] = pydantic_xml.element(tag='emulator', default=None)
	machine_list: typing.Optional[typing.List[_machine]] = pydantic_xml.element(tag='machine', default=None)

_domain = domain

class guestcaps_arch(pydantic_xml.BaseXmlModel, tag='arch', search_mode='unordered'):
	name: typing.Literal['aarch64', 'alpha', 'armv6l', 'armv7l', 'cris', 'i686', 'ia64', 'lm32', 'loongarch64', 'm68k', 'microblaze', 'microblazeel', 'mips', 'mipsel', 'mips64', 'mips64el', 'openrisc', 'parisc', 'parisc64', 'ppc', 'ppc64', 'ppc64le', 'ppcemb', 'riscv32', 'riscv64', 's390', 's390x', 'sh4', 'sh4eb', 'sparc', 'sparc64', 'unicore32', 'x86_64', 'xtensa', 'xtensaeb'] = pydantic_xml.attr(name='name')
	wordsize: _wordsize = pydantic_xml.element(tag='wordsize')
	emulator: typing.Optional[_emulator] = pydantic_xml.element(tag='emulator', default=None)
	loader: typing.Optional[_loader] = pydantic_xml.element(tag='loader', default=None)
	machine_list: typing.Optional[typing.List[_machine]] = pydantic_xml.element(tag='machine', default=None)
	domain_list: typing.List[_domain] = pydantic_xml.element(tag='domain', min_length=1)

_guestcaps_arch = guestcaps_arch

class ia64_be(pydantic_xml.BaseXmlModel, tag='ia64_be', search_mode='strict'):
	pass

_ia64_be = ia64_be

class acpi(pydantic_xml.BaseXmlModel, tag='acpi', search_mode='strict'):
	toggle: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='toggle')
	default: typing.Literal['on', 'off'] = pydantic_xml.attr(name='default')

_acpi = acpi

class apic(pydantic_xml.BaseXmlModel, tag='apic', search_mode='strict'):
	toggle: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='toggle')
	default: typing.Literal['on', 'off'] = pydantic_xml.attr(name='default')

_apic = apic

class cpuselection(pydantic_xml.BaseXmlModel, tag='cpuselection', search_mode='strict'):
	pass

_cpuselection = cpuselection

class deviceboot(pydantic_xml.BaseXmlModel, tag='deviceboot', search_mode='strict'):
	pass

_deviceboot = deviceboot

class disksnapshot(pydantic_xml.BaseXmlModel, tag='disksnapshot', search_mode='strict'):
	toggle: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='toggle')
	default: typing.Literal['on', 'off'] = pydantic_xml.attr(name='default')

_disksnapshot = disksnapshot

class hap(pydantic_xml.BaseXmlModel, tag='hap', search_mode='strict'):
	toggle: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='toggle')
	default: typing.Literal['on', 'off'] = pydantic_xml.attr(name='default')

_hap = hap

class external_snapshot(pydantic_xml.BaseXmlModel, tag='externalSnapshot', search_mode='strict'):
	pass

_external_snapshot = external_snapshot

class guestcaps_features(pydantic_xml.BaseXmlModel, tag='features', search_mode='unordered'):
	pae: typing.Optional[_pae] = pydantic_xml.element(tag='pae', default=None)
	nonpae: typing.Optional[_nonpae] = pydantic_xml.element(tag='nonpae', default=None)
	ia64_be: typing.Optional[_ia64_be] = pydantic_xml.element(tag='ia64_be', default=None)
	acpi: typing.Optional[_acpi] = pydantic_xml.element(tag='acpi', default=None)
	apic: typing.Optional[_apic] = pydantic_xml.element(tag='apic', default=None)
	cpuselection: typing.Optional[_cpuselection] = pydantic_xml.element(tag='cpuselection', default=None)
	deviceboot: typing.Optional[_deviceboot] = pydantic_xml.element(tag='deviceboot', default=None)
	disksnapshot: typing.Optional[_disksnapshot] = pydantic_xml.element(tag='disksnapshot', default=None)
	hap: typing.Optional[_hap] = pydantic_xml.element(tag='hap', default=None)
	external_snapshot: typing.Optional[_external_snapshot] = pydantic_xml.element(tag='externalSnapshot', default=None)

_guestcaps_features = guestcaps_features

class guestcaps(pydantic_xml.BaseXmlModel, tag='guest', search_mode='strict'):
	os_type: _ostype = pydantic_xml.element(tag='os_type')
	arch: _guestcaps_arch = pydantic_xml.element(tag='arch')
	features: typing.Optional[_guestcaps_features] = pydantic_xml.element(tag='features', default=None)

_guestcaps = guestcaps

class capabilities(pydantic_xml.BaseXmlModel, tag='capabilities', search_mode='unordered'):
	host: _hostcaps = pydantic_xml.element(tag='host')
	guest_list: typing.Optional[typing.List[_guestcaps]] = pydantic_xml.element(tag='guest', default=None)

_capabilities = capabilities

capability = _capabilities

