import typing
import pydantic
import pydantic_xml

# This file was automatically generated by relaxng-to-pydantic. Do not modify.
class cpu_model(pydantic_xml.BaseXmlModel, tag='model', search_mode='unordered'):
	value: typing.Optional[str] = None
	fallback: typing.Optional[typing.Literal['allow', 'forbid']] = pydantic_xml.attr(name='fallback', default=None)
	vendor_id: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='[^,]{12}')]] = pydantic_xml.attr(name='vendor_id', default=None)

_cpu_model = cpu_model

class cpu_vendor(pydantic_xml.BaseXmlModel, tag='vendor', search_mode='strict'):
	value: str

_cpu_vendor = cpu_vendor

class cpu_topology(pydantic_xml.BaseXmlModel, tag='topology', search_mode='strict'):
	sockets: int = pydantic_xml.attr(name='sockets')
	dies: typing.Optional[int] = pydantic_xml.attr(name='dies', default=None)
	clusters: typing.Optional[int] = pydantic_xml.attr(name='clusters', default=None)
	cores: int = pydantic_xml.attr(name='cores')
	threads: int = pydantic_xml.attr(name='threads')

_cpu_topology = cpu_topology

class cpu_feature(pydantic_xml.BaseXmlModel, tag='feature', search_mode='strict'):
	policy: typing.Literal['force', 'require', 'optional', 'disable', 'forbid'] = pydantic_xml.attr(name='policy')
	name: typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9\\-_\\.]+')] = pydantic_xml.attr(name='name')

_cpu_feature = cpu_feature

class numa_distance(pydantic_xml.BaseXmlModel, tag='sibling', search_mode='strict'):
	id: int = pydantic_xml.attr(name='id')
	value: int = pydantic_xml.attr(name='value')

_numa_distance = numa_distance

class distances(pydantic_xml.BaseXmlModel, tag='distances', search_mode='unordered'):
	sibling_list: typing.List[_numa_distance] = pydantic_xml.element(tag='sibling', min_length=1)

_distances = distances

class size(pydantic_xml.BaseXmlModel, tag='size', search_mode='strict'):
	value: int = pydantic_xml.attr(name='value')
	unit: typing.Annotated[str, pydantic.Field(pattern='([bB]([yY][tT][eE][sS]?)?)|([kKmMgGtTpPeE]([iI]?[bB])?)')] = pydantic_xml.attr(name='unit')

_size = size

class line(pydantic_xml.BaseXmlModel, tag='line', search_mode='strict'):
	value: int = pydantic_xml.attr(name='value')
	unit: typing.Annotated[str, pydantic.Field(pattern='([bB]([yY][tT][eE][sS]?)?)|([kKmMgGtTpPeE]([iI]?[bB])?)')] = pydantic_xml.attr(name='unit')

_line = line

class numa_cache(pydantic_xml.BaseXmlModel, tag='cache', search_mode='unordered'):
	level: int = pydantic_xml.attr(name='level')
	associativity: typing.Literal['none', 'direct', 'full'] = pydantic_xml.attr(name='associativity')
	policy: typing.Literal['none', 'writeback', 'writethrough'] = pydantic_xml.attr(name='policy')
	size: _size = pydantic_xml.element(tag='size')
	line: _line = pydantic_xml.element(tag='line')

_numa_cache = numa_cache

class numa_cell(pydantic_xml.BaseXmlModel, tag='cell', search_mode='unordered'):
	id: typing.Optional[int] = pydantic_xml.attr(name='id', default=None)
	cpus: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='([0-9]+(-[0-9]+)?|\\^[0-9]+)(,([0-9]+(-[0-9]+)?|\\^[0-9]+))*')]] = pydantic_xml.attr(name='cpus', default=None)
	memory: int = pydantic_xml.attr(name='memory')
	unit: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='([bB]([yY][tT][eE][sS]?)?)|([kKmMgGtTpPeE]([iI]?[bB])?)')]] = pydantic_xml.attr(name='unit', default=None)
	mem_access: typing.Optional[typing.Literal['shared', 'private']] = pydantic_xml.attr(name='memAccess', default=None)
	discard: typing.Optional[typing.Literal['yes', 'no']] = pydantic_xml.attr(name='discard', default=None)
	distances: typing.Optional[_distances] = pydantic_xml.element(tag='distances', default=None)
	cache_list: typing.Optional[typing.List[_numa_cache]] = pydantic_xml.element(tag='cache', default=None)

_numa_cell = numa_cell

class latency(pydantic_xml.BaseXmlModel, tag='latency', search_mode='strict'):
	initiator: int = pydantic_xml.attr(name='initiator')
	target: int = pydantic_xml.attr(name='target')
	cache: typing.Optional[int] = pydantic_xml.attr(name='cache', default=None)
	type: typing.Literal['access', 'read', 'write'] = pydantic_xml.attr(name='type')
	value: int = pydantic_xml.attr(name='value')

_latency = latency

class bandwidth(pydantic_xml.BaseXmlModel, tag='bandwidth', search_mode='strict'):
	initiator: int = pydantic_xml.attr(name='initiator')
	target: int = pydantic_xml.attr(name='target')
	cache: typing.Optional[int] = pydantic_xml.attr(name='cache', default=None)
	type: typing.Literal['access', 'read', 'write'] = pydantic_xml.attr(name='type')
	value: int = pydantic_xml.attr(name='value')
	unit: typing.Annotated[str, pydantic.Field(pattern='([bB]([yY][tT][eE][sS]?)?)|([kKmMgGtTpPeE]([iI]?[bB])?)')] = pydantic_xml.attr(name='unit')

_bandwidth = bandwidth

class numa_interconnects(pydantic_xml.BaseXmlModel, tag='interconnects', search_mode='unordered'):
	latency_list: typing.Optional[typing.List[_latency]] = pydantic_xml.element(tag='latency', default=None)
	bandwidth_list: typing.Optional[typing.List[_bandwidth]] = pydantic_xml.element(tag='bandwidth', default=None)

_numa_interconnects = numa_interconnects

class cpu_numa(pydantic_xml.BaseXmlModel, tag='numa', search_mode='unordered'):
	cell_list: typing.List[_numa_cell] = pydantic_xml.element(tag='cell', min_length=1)
	interconnects: typing.Optional[_numa_interconnects] = pydantic_xml.element(tag='interconnects', default=None)

_cpu_numa = cpu_numa

class cpu_cache(pydantic_xml.BaseXmlModel, tag='cache', search_mode='strict'):
	level: typing.Optional[typing.Literal['1', '2', '3']] = pydantic_xml.attr(name='level', default=None)
	mode: typing.Literal['emulate', 'passthrough', 'disable'] = pydantic_xml.attr(name='mode')

_cpu_cache = cpu_cache

class cpu_max_phys_addr(pydantic_xml.BaseXmlModel, tag='maxphysaddr', search_mode='strict'):
	mode: typing.Literal['emulate', 'passthrough'] = pydantic_xml.attr(name='mode')
	bits: typing.Optional[int] = pydantic_xml.attr(name='bits', default=None)
	limit: typing.Optional[int] = pydantic_xml.attr(name='limit', default=None)

_cpu_max_phys_addr = cpu_max_phys_addr

class guestcpu(pydantic_xml.BaseXmlModel, tag='cpu', search_mode='unordered'):
	mode: typing.Optional[typing.Literal['custom', 'host-model', 'host-passthrough', 'maximum']] = pydantic_xml.attr(name='mode', default=None)
	match: typing.Optional[typing.Literal['minimum', 'exact', 'strict']] = pydantic_xml.attr(name='match', default=None)
	check: typing.Optional[typing.Literal['none', 'partial', 'full']] = pydantic_xml.attr(name='check', default=None)
	deprecated_features: typing.Optional[typing.Literal['on', 'off']] = pydantic_xml.attr(name='deprecated_features', default=None)
	migratable: typing.Optional[typing.Literal['on', 'off']] = pydantic_xml.attr(name='migratable', default=None)
	model: typing.Optional[_cpu_model] = pydantic_xml.element(tag='model', default=None)
	vendor: typing.Optional[_cpu_vendor] = pydantic_xml.element(tag='vendor', default=None)
	topology: typing.Optional[_cpu_topology] = pydantic_xml.element(tag='topology', default=None)
	feature_list: typing.Optional[typing.List[_cpu_feature]] = pydantic_xml.element(tag='feature', default=None)
	numa: typing.Optional[_cpu_numa] = pydantic_xml.element(tag='numa', default=None)
	cache: typing.Optional[_cpu_cache] = pydantic_xml.element(tag='cache', default=None)
	maxphysaddr: typing.Optional[_cpu_max_phys_addr] = pydantic_xml.element(tag='maxphysaddr', default=None)

_guestcpu = guestcpu

class arch(pydantic_xml.BaseXmlModel, tag='arch', search_mode='unordered'):
	value: typing.Literal['aarch64', 'alpha', 'armv6l', 'armv7l', 'cris', 'i686', 'ia64', 'lm32', 'loongarch64', 'm68k', 'microblaze', 'microblazeel', 'mips', 'mipsel', 'mips64', 'mips64el', 'openrisc', 'parisc', 'parisc64', 'ppc', 'ppc64', 'ppc64le', 'ppcemb', 'riscv32', 'riscv64', 's390', 's390x', 'sh4', 'sh4eb', 'sparc', 'sparc64', 'unicore32', 'x86_64', 'xtensa', 'xtensaeb']

_arch = arch

class pae(pydantic_xml.BaseXmlModel, tag='pae', search_mode='strict'):
	pass

_pae = pae

class nonpae(pydantic_xml.BaseXmlModel, tag='nonpae', search_mode='strict'):
	pass

_nonpae = nonpae

class vmx(pydantic_xml.BaseXmlModel, tag='vmx', search_mode='strict'):
	pass

_vmx = vmx

class svm(pydantic_xml.BaseXmlModel, tag='svm', search_mode='strict'):
	pass

_svm = svm

class features(pydantic_xml.BaseXmlModel, tag='features', search_mode='strict'):
	pae: typing.Optional[_pae] = pydantic_xml.element(tag='pae', default=None)
	nonpae: typing.Optional[_nonpae] = pydantic_xml.element(tag='nonpae', default=None)
	vmx: typing.Optional[_vmx] = pydantic_xml.element(tag='vmx', default=None)
	svm: typing.Optional[_svm] = pydantic_xml.element(tag='svm', default=None)

_features = features

class model(pydantic_xml.BaseXmlModel, tag='model', search_mode='strict'):
	value: str

_model = model

class microcode(pydantic_xml.BaseXmlModel, tag='microcode', search_mode='strict'):
	version: int = pydantic_xml.attr(name='version')

_microcode = microcode

class signature(pydantic_xml.BaseXmlModel, tag='signature', search_mode='strict'):
	family: int = pydantic_xml.attr(name='family')
	model: int = pydantic_xml.attr(name='model')
	stepping: int = pydantic_xml.attr(name='stepping')

_signature = signature

class counter(pydantic_xml.BaseXmlModel, tag='counter', search_mode='strict'):
	name: str = pydantic_xml.attr(name='name')
	frequency: int = pydantic_xml.attr(name='frequency')
	scaling: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='scaling')

_counter = counter

class feature(pydantic_xml.BaseXmlModel, tag='feature', search_mode='strict'):
	name: typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9\\-_]+')] = pydantic_xml.attr(name='name')

_feature = feature

class pages(pydantic_xml.BaseXmlModel, tag='pages', search_mode='strict'):
	unit: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='([bB]([yY][tT][eE][sS]?)?)|([kKmMgGtTpPeE]([iI]?[bB])?)')]] = pydantic_xml.attr(name='unit', default=None)
	size: int = pydantic_xml.attr(name='size')

_pages = pages

class hostcpu(pydantic_xml.BaseXmlModel, tag='cpu', search_mode='unordered'):
	arch: _arch = pydantic_xml.element(tag='arch')
	features: typing.Optional[_features] = pydantic_xml.element(tag='features', default=None)
	model: typing.Optional[_model] = pydantic_xml.element(tag='model', default=None)
	vendor: typing.Optional[_cpu_vendor] = pydantic_xml.element(tag='vendor', default=None)
	microcode: typing.Optional[_microcode] = pydantic_xml.element(tag='microcode', default=None)
	signature: typing.Optional[_signature] = pydantic_xml.element(tag='signature', default=None)
	counter: typing.Optional[_counter] = pydantic_xml.element(tag='counter', default=None)
	topology: typing.Optional[_cpu_topology] = pydantic_xml.element(tag='topology', default=None)
	maxphysaddr: typing.Optional[_cpu_max_phys_addr] = pydantic_xml.element(tag='maxphysaddr', default=None)
	feature_list: typing.Optional[typing.List[_feature]] = pydantic_xml.element(tag='feature', default=None)
	pages_list: typing.Optional[typing.List[_pages]] = pydantic_xml.element(tag='pages', default=None)

_hostcpu = hostcpu

cpu = typing.Union[_guestcpu, _hostcpu]

