import typing
import pydantic
import pydantic_xml

# This file was automatically generated by relaxng-to-pydantic. Do not modify.
class name(pydantic_xml.BaseXmlModel, tag='name', search_mode='strict'):
	value: str

_name = name

class description(pydantic_xml.BaseXmlModel, tag='description', search_mode='strict'):
	value: str

_description = description

class state(pydantic_xml.BaseXmlModel, tag='state', search_mode='unordered'):
	value: typing.Literal['running', 'blocked', 'paused', 'shutdown', 'shutoff', 'crashed', 'disk-snapshot']

_state = state

class creation_time(pydantic_xml.BaseXmlModel, tag='creationTime', search_mode='strict'):
	value: str

_creation_time = creation_time

class memory(pydantic_xml.BaseXmlModel, tag='memory', search_mode='unordered'):
	snapshot: typing.Optional[typing.Literal['no', 'internal', 'external']] = pydantic_xml.attr(name='snapshot', default=None)
	file: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='(/|[a-zA-Z]:\\\\).+')]] = pydantic_xml.attr(name='file', default=None)

_memory = memory

class label(pydantic_xml.BaseXmlModel, tag='label', search_mode='strict'):
	value: str

_label = label

class dev_seclabel(pydantic_xml.BaseXmlModel, tag='seclabel', search_mode='unordered'):
	model: typing.Optional[str] = pydantic_xml.attr(name='model', default=None)
	relabel: typing.Optional[typing.Literal['no', 'yes']] = pydantic_xml.attr(name='relabel', default=None)
	labelskip: typing.Optional[typing.Literal['yes']] = pydantic_xml.attr(name='labelskip', default=None)
	label_list: typing.Optional[typing.List[_label]] = pydantic_xml.element(tag='label', default=None)

_dev_seclabel = dev_seclabel

class slice(pydantic_xml.BaseXmlModel, tag='slice', search_mode='strict'):
	type: typing.Literal['storage'] = pydantic_xml.attr(name='type')
	offset: int = pydantic_xml.attr(name='offset')
	size: int = pydantic_xml.attr(name='size')

_slice = slice

class slices(pydantic_xml.BaseXmlModel, tag='slices', search_mode='strict'):
	slice: _slice = pydantic_xml.element(tag='slice')

_slices = slices

class max_size(pydantic_xml.BaseXmlModel, tag='max_size', search_mode='strict'):
	value: int
	unit: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='([bB]([yY][tT][eE][sS]?)?)|([kKmMgGtTpPeE]([iI]?[bB])?)')]] = pydantic_xml.attr(name='unit', default=None)

_max_size = max_size

class metadata_cache(pydantic_xml.BaseXmlModel, tag='metadata_cache', search_mode='strict'):
	max_size: typing.Optional[_max_size] = pydantic_xml.element(tag='max_size', default=None)

_metadata_cache = metadata_cache

class disk_format(pydantic_xml.BaseXmlModel, tag='format', search_mode='strict'):
	type: typing.Literal['raw', 'dir', 'bochs', 'cloop', 'dmg', 'iso', 'vpc', 'vdi', 'fat', 'vhd', 'ploop', 'luks', 'cow', 'qcow', 'qcow2', 'qed', 'vmdk'] = pydantic_xml.attr(name='type')
	metadata_cache: typing.Optional[_metadata_cache] = pydantic_xml.element(tag='metadata_cache', default=None)

_disk_format = disk_format

class secret(pydantic_xml.BaseXmlModel, tag='secret', search_mode='unordered'):
	type: typing.Literal['passphrase'] = pydantic_xml.attr(name='type')
	uuid: typing.Optional[typing.Union[typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{32}')], typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{8}\\-([a-fA-F0-9]{4}\\-){3}[a-fA-F0-9]{12}')]]] = pydantic_xml.attr(name='uuid', default=None)
	usage: typing.Optional[str] = pydantic_xml.attr(name='usage', default=None)

_secret = secret

class cipher(pydantic_xml.BaseXmlModel, tag='cipher', search_mode='strict'):
	name: str = pydantic_xml.attr(name='name')
	size: int = pydantic_xml.attr(name='size')
	mode: typing.Optional[str] = pydantic_xml.attr(name='mode', default=None)
	hash: typing.Optional[str] = pydantic_xml.attr(name='hash', default=None)

_cipher = cipher

class ivgen(pydantic_xml.BaseXmlModel, tag='ivgen', search_mode='strict'):
	name: str = pydantic_xml.attr(name='name')
	hash: typing.Optional[str] = pydantic_xml.attr(name='hash', default=None)

_ivgen = ivgen

class encryption(pydantic_xml.BaseXmlModel, tag='encryption', search_mode='unordered'):
	format: typing.Literal['default', 'qcow', 'luks', 'luks2', 'luks-any'] = pydantic_xml.attr(name='format')
	engine: typing.Optional[typing.Literal['qemu', 'librbd']] = pydantic_xml.attr(name='engine', default=None)
	secret_list: typing.Optional[typing.List[_secret]] = pydantic_xml.element(tag='secret', min_length=1, default=None)
	cipher: typing.Optional[_cipher] = pydantic_xml.element(tag='cipher', default=None)
	ivgen: typing.Optional[_ivgen] = pydantic_xml.element(tag='ivgen', default=None)

_encryption = encryption

class reconnect(pydantic_xml.BaseXmlModel, tag='reconnect', search_mode='unordered'):
	enabled: typing.Optional[typing.Literal['yes', 'no']] = pydantic_xml.attr(name='enabled', default=None)
	timeout: typing.Optional[int] = pydantic_xml.attr(name='timeout', default=None)
	delay: typing.Optional[int] = pydantic_xml.attr(name='delay', default=None)

_reconnect = reconnect

class unix_socket_source(pydantic_xml.BaseXmlModel, tag='source', search_mode='strict'):
	type: typing.Literal['unix'] = pydantic_xml.attr(name='type')
	path: typing.Annotated[str, pydantic.Field(pattern='(/|[a-zA-Z]:\\\\).+')] = pydantic_xml.attr(name='path')
	mode: typing.Literal['server', 'client'] = pydantic_xml.attr(name='mode')
	reconnect: typing.Optional[_reconnect] = pydantic_xml.element(tag='reconnect', default=None)

_unix_socket_source = unix_socket_source

class reservations(pydantic_xml.BaseXmlModel, tag='reservations', search_mode='strict'):
	managed: typing.Optional[typing.Literal['yes', 'no']] = pydantic_xml.attr(name='managed', default=None)
	source: typing.Optional[_unix_socket_source] = pydantic_xml.element(tag='source', default=None)

_reservations = reservations

class disk_source_network_host(pydantic_xml.BaseXmlModel, tag='host', search_mode='unordered'):
	model_config = {'extra': 'forbid'}
	transport: typing.Optional[typing.Literal['tcp', 'rdma', 'unix']] = pydantic_xml.attr(name='transport', default=None)
	name: typing.Optional[typing.Union[typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9\\.\\-]+')], typing.Union[typing.Annotated[str, pydantic.Field(pattern='(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))')], typing.Annotated[str, pydantic.Field(pattern='(([0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){6}:[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){5}:([0-9A-Fa-f]{1,4}:)?[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){4}:([0-9A-Fa-f]{1,4}:){0,2}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){3}:([0-9A-Fa-f]{1,4}:){0,3}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){2}:([0-9A-Fa-f]{1,4}:){0,4}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){6}(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|(([0-9A-Fa-f]{1,4}:){0,5}:(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|(::([0-9A-Fa-f]{1,4}:){0,5}(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|([0-9A-Fa-f]{1,4}::([0-9A-Fa-f]{1,4}:){0,5}[0-9A-Fa-f]{1,4})|(::([0-9A-Fa-f]{1,4}:){0,6}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){1,7}:)|(::)')]]]] = pydantic_xml.attr(name='name', default=None)
	port: typing.Optional[int] = pydantic_xml.attr(name='port', default=None)
	socket: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='(/|[a-zA-Z]:\\\\).+')]] = pydantic_xml.attr(name='socket', default=None)

_disk_source_network_host = disk_source_network_host

class snapshot(pydantic_xml.BaseXmlModel, tag='snapshot', search_mode='strict'):
	name: typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9_\\+\\-]+')] = pydantic_xml.attr(name='name')

_snapshot = snapshot

class config(pydantic_xml.BaseXmlModel, tag='config', search_mode='strict'):
	file: typing.Annotated[str, pydantic.Field(pattern='(/|[a-zA-Z]:\\\\).+')] = pydantic_xml.attr(name='file')

_config = config

class disk_auth_secret(pydantic_xml.BaseXmlModel, tag='secret', search_mode='unordered'):
	type: typing.Literal['ceph', 'iscsi'] = pydantic_xml.attr(name='type')
	uuid: typing.Optional[typing.Union[typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{32}')], typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{8}\\-([a-fA-F0-9]{4}\\-){3}[a-fA-F0-9]{12}')]]] = pydantic_xml.attr(name='uuid', default=None)
	usage: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='[^/\\n]+')]] = pydantic_xml.attr(name='usage', default=None)

_disk_auth_secret = disk_auth_secret

class disk_auth(pydantic_xml.BaseXmlModel, tag='auth', search_mode='strict'):
	username: typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9_\\+\\-]+')] = pydantic_xml.attr(name='username')
	secret: _disk_auth_secret = pydantic_xml.element(tag='secret')

_disk_auth = disk_auth

class iqn(pydantic_xml.BaseXmlModel, tag='iqn', search_mode='strict'):
	name: str = pydantic_xml.attr(name='name')

_iqn = iqn

class initiatorinfo(pydantic_xml.BaseXmlModel, tag='initiator', search_mode='strict'):
	iqn: _iqn = pydantic_xml.element(tag='iqn')

_initiatorinfo = initiatorinfo

class disk_source_network_protocol_h_t_t_p_cookies_cookie(pydantic_xml.BaseXmlModel, tag='cookie', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='"?[!#$%&\'()*+\\-./0-9:>=<?@A-Z\\^_`\\[\\]a-z|~]+"?')]
	name: typing.Annotated[str, pydantic.Field(pattern="[!#$%&'*+\\-.0-9A-Z\\^_`a-z|~]+")] = pydantic_xml.attr(name='name')

_disk_source_network_protocol_h_t_t_p_cookies_cookie = disk_source_network_protocol_h_t_t_p_cookies_cookie

class disk_source_network_protocol_h_t_t_p_cookies(pydantic_xml.BaseXmlModel, tag='cookies', search_mode='unordered'):
	cookie_list: typing.List[_disk_source_network_protocol_h_t_t_p_cookies_cookie] = pydantic_xml.element(tag='cookie', min_length=1)

_disk_source_network_protocol_h_t_t_p_cookies = disk_source_network_protocol_h_t_t_p_cookies

class readahead(pydantic_xml.BaseXmlModel, tag='readahead', search_mode='strict'):
	size: int = pydantic_xml.attr(name='size')

_readahead = readahead

class timeout(pydantic_xml.BaseXmlModel, tag='timeout', search_mode='strict'):
	seconds: int = pydantic_xml.attr(name='seconds')

_timeout = timeout

class disk_source_network_protocol_s_s_l_verify(pydantic_xml.BaseXmlModel, tag='ssl', search_mode='strict'):
	verify: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='verify')

_disk_source_network_protocol_s_s_l_verify = disk_source_network_protocol_s_s_l_verify

class disk_source_network_protocol_s_s_h_host_verify(pydantic_xml.BaseXmlModel, tag='knownHosts', search_mode='strict'):
	path: typing.Annotated[str, pydantic.Field(pattern='(/|[a-zA-Z]:\\\\).+')] = pydantic_xml.attr(name='path')

_disk_source_network_protocol_s_s_h_host_verify = disk_source_network_protocol_s_s_h_host_verify

class source_identity(pydantic_xml.BaseXmlModel, tag='identity', search_mode='unordered'):
	username: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9_\\+\\-]+')]] = pydantic_xml.attr(name='username', default=None)
	keyfile: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='(/|[a-zA-Z]:\\\\).+')]] = pydantic_xml.attr(name='keyfile', default=None)
	agentsock: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='(/|[a-zA-Z]:\\\\).+')]] = pydantic_xml.attr(name='agentsock', default=None)
	user: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9_\\+\\-]+')]] = pydantic_xml.attr(name='user', default=None)
	group: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9_\\+\\-]+')]] = pydantic_xml.attr(name='group', default=None)

_source_identity = source_identity

class address(pydantic_xml.BaseXmlModel, tag='address', search_mode='strict'):
	domain: typing.Optional[typing.Annotated[int, pydantic.BeforeValidator(lambda v: (int(v) if v.isdigit() else int(v, 16)) if isinstance(v, str) else v)]] = pydantic_xml.attr(name='domain', default=None)
	bus: typing.Optional[typing.Annotated[int, pydantic.BeforeValidator(lambda v: (int(v) if v.isdigit() else int(v, 16)) if isinstance(v, str) else v)]] = pydantic_xml.attr(name='bus', default=None)
	slot: typing.Optional[typing.Annotated[int, pydantic.BeforeValidator(lambda v: (int(v) if v.isdigit() else int(v, 16)) if isinstance(v, str) else v)]] = pydantic_xml.attr(name='slot', default=None)
	function: typing.Optional[typing.Annotated[int, pydantic.BeforeValidator(lambda v: (int(v) if v.isdigit() else int(v, 16)) if isinstance(v, str) else v)]] = pydantic_xml.attr(name='function', default=None)
	multifunction: typing.Optional[typing.Literal['on', 'off']] = pydantic_xml.attr(name='multifunction', default=None)

_address = address

class disk_source(pydantic_xml.BaseXmlModel, tag='source', search_mode='unordered'):
	file: typing.Optional[typing.Union[typing.Annotated[str, pydantic.Field(pattern='(/|[a-zA-Z]:\\\\).+')], typing.Annotated[str, pydantic.Field(pattern='\\[[^\\]]+\\] .+')]]] = pydantic_xml.attr(name='file', default=None)
	fdgroup: typing.Optional[str] = pydantic_xml.attr(name='fdgroup', default=None)
	encryption: typing.Optional[_encryption] = pydantic_xml.element(tag='encryption', default=None)
	seclabel_list: typing.Optional[typing.List[_dev_seclabel]] = pydantic_xml.element(tag='seclabel', default=None)
	dev: typing.Optional[typing.Union[typing.Union[typing.Annotated[str, pydantic.Field(pattern='(/|[a-zA-Z]:\\\\).+')], typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9_\\.\\-\\\\:/]+')]], typing.Annotated[str, pydantic.Field(pattern='(/|[a-zA-Z]:\\\\).+')]]] = pydantic_xml.attr(name='dev', default=None)
	reservations: typing.Optional[_reservations] = pydantic_xml.element(tag='reservations', default=None)
	dir: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='(/|[a-zA-Z]:\\\\).+')]] = pydantic_xml.attr(name='dir', default=None)
	protocol: typing.Optional[typing.Literal['nbd', 'gluster', 'rbd', 'iscsi', 'http', 'https', 'ftps', 'ftp', 'ssh', 'sheepdog', 'tftp', 'vxhs', 'nfs']] = pydantic_xml.attr(name='protocol', default=None)
	name: typing.Optional[str] = pydantic_xml.attr(name='name', default=None)
	tls: typing.Optional[typing.Literal['yes', 'no']] = pydantic_xml.attr(name='tls', default=None)
	tls_hostname: typing.Optional[str] = pydantic_xml.attr(name='tlsHostname', default=None)
	host: typing.Optional[typing.List[typing.Union[_disk_source_network_host, _disk_source_network_host]]] = pydantic_xml.element(tag='host', default=None)
	reconnect: typing.Optional[_reconnect] = pydantic_xml.element(tag='reconnect', default=None)
	snapshot: typing.Optional[_snapshot] = pydantic_xml.element(tag='snapshot', default=None)
	config: typing.Optional[_config] = pydantic_xml.element(tag='config', default=None)
	auth: typing.Optional[_disk_auth] = pydantic_xml.element(tag='auth', default=None)
	initiator: typing.Optional[_initiatorinfo] = pydantic_xml.element(tag='initiator', default=None)
	query: typing.Optional[str] = pydantic_xml.attr(name='query', default=None)
	cookies: typing.Optional[_disk_source_network_protocol_h_t_t_p_cookies] = pydantic_xml.element(tag='cookies', default=None)
	readahead: typing.Optional[_readahead] = pydantic_xml.element(tag='readahead', default=None)
	timeout: typing.Optional[_timeout] = pydantic_xml.element(tag='timeout', default=None)
	ssl: typing.Optional[_disk_source_network_protocol_s_s_l_verify] = pydantic_xml.element(tag='ssl', default=None)
	known_hosts: typing.Optional[_disk_source_network_protocol_s_s_h_host_verify] = pydantic_xml.element(tag='knownHosts', default=None)
	identity: typing.Optional[_source_identity] = pydantic_xml.element(tag='identity', default=None)
	pool: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='[^/\\n]+')]] = pydantic_xml.attr(name='pool', default=None)
	volume: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='[^/]+')]] = pydantic_xml.attr(name='volume', default=None)
	mode: typing.Optional[typing.Literal['host', 'direct']] = pydantic_xml.attr(name='mode', default=None)
	type: typing.Optional[typing.Literal['pci', 'unix']] = pydantic_xml.attr(name='type', default=None)
	namespace: typing.Optional[typing.Annotated[int, pydantic.BeforeValidator(lambda v: (int(v) if v.isdigit() else int(v, 16)) if isinstance(v, str) else v)]] = pydantic_xml.attr(name='namespace', default=None)
	managed: typing.Optional[typing.Literal['yes', 'no']] = pydantic_xml.attr(name='managed', default=None)
	address: typing.Optional[_address] = pydantic_xml.element(tag='address', default=None)
	path: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='(/|[a-zA-Z]:\\\\).+')]] = pydantic_xml.attr(name='path', default=None)

_disk_source = disk_source

class disk_source_common_data_store(pydantic_xml.BaseXmlModel, tag='dataStore', search_mode='unordered'):
	format: _disk_format = pydantic_xml.element(tag='format')
	type: typing.Optional[typing.Literal['file', 'block', 'dir', 'network', 'volume', 'nvme', 'vhostuser', 'vhostvdpa', 'ctl']] = pydantic_xml.attr(name='type', default=None)
	source: typing.Optional[_disk_source] = pydantic_xml.element(tag='source', default=None)

_disk_source_common_data_store = disk_source_common_data_store

class private_data(pydantic_xml.BaseXmlModel, tag='privateData', search_mode='strict'):
	pass

_private_data = private_data

class driver(pydantic_xml.BaseXmlModel, tag='driver', search_mode='strict'):
	type: typing.Optional[typing.Literal['cow', 'qcow', 'qcow2', 'qed', 'vmdk']] = pydantic_xml.attr(name='type', default=None)
	metadata_cache: typing.Optional[_metadata_cache] = pydantic_xml.element(tag='metadata_cache', default=None)

_driver = driver

class snapshot_delete_in_progress(pydantic_xml.BaseXmlModel, tag='snapshotDeleteInProgress', search_mode='strict'):
	pass

_snapshot_delete_in_progress = snapshot_delete_in_progress

class disksnapshot_Variant_source(pydantic_xml.BaseXmlModel, tag='source', search_mode='unordered'):
	file: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='(/|[a-zA-Z]:\\\\).+')]] = pydantic_xml.attr(name='file', default=None)
	seclabel_list: typing.Optional[typing.List[_dev_seclabel]] = pydantic_xml.element(tag='seclabel', default=None)
	index: typing.Optional[int] = pydantic_xml.attr(name='index', default=None)
	slices: typing.Optional[_slices] = pydantic_xml.element(tag='slices', default=None)
	data_store: typing.Optional[_disk_source_common_data_store] = pydantic_xml.element(tag='dataStore', default=None)
	private_data: typing.Optional[_private_data] = pydantic_xml.element(tag='privateData', default=None)
	encryption: typing.Optional[_encryption] = pydantic_xml.element(tag='encryption', default=None)
	dev: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='(/|[a-zA-Z]:\\\\).+')]] = pydantic_xml.attr(name='dev', default=None)
	protocol: typing.Optional[typing.Literal['nbd', 'gluster', 'rbd', 'iscsi', 'http', 'https', 'ftps', 'ftp', 'ssh', 'sheepdog', 'tftp', 'vxhs', 'nfs']] = pydantic_xml.attr(name='protocol', default=None)
	name: typing.Optional[str] = pydantic_xml.attr(name='name', default=None)
	tls: typing.Optional[typing.Literal['yes', 'no']] = pydantic_xml.attr(name='tls', default=None)
	tls_hostname: typing.Optional[str] = pydantic_xml.attr(name='tlsHostname', default=None)
	host: typing.Optional[typing.List[typing.Union[_disk_source_network_host, _disk_source_network_host]]] = pydantic_xml.element(tag='host', default=None)
	reconnect: typing.Optional[_reconnect] = pydantic_xml.element(tag='reconnect', default=None)
	snapshot: typing.Optional[_snapshot] = pydantic_xml.element(tag='snapshot', default=None)
	config: typing.Optional[_config] = pydantic_xml.element(tag='config', default=None)
	auth: typing.Optional[_disk_auth] = pydantic_xml.element(tag='auth', default=None)
	initiator: typing.Optional[_initiatorinfo] = pydantic_xml.element(tag='initiator', default=None)
	query: typing.Optional[str] = pydantic_xml.attr(name='query', default=None)
	cookies: typing.Optional[_disk_source_network_protocol_h_t_t_p_cookies] = pydantic_xml.element(tag='cookies', default=None)
	readahead: typing.Optional[_readahead] = pydantic_xml.element(tag='readahead', default=None)
	timeout: typing.Optional[_timeout] = pydantic_xml.element(tag='timeout', default=None)
	ssl: typing.Optional[_disk_source_network_protocol_s_s_l_verify] = pydantic_xml.element(tag='ssl', default=None)
	known_hosts: typing.Optional[_disk_source_network_protocol_s_s_h_host_verify] = pydantic_xml.element(tag='knownHosts', default=None)
	identity: typing.Optional[_source_identity] = pydantic_xml.element(tag='identity', default=None)

_disksnapshot_Variant_source = disksnapshot_Variant_source

class disksnapshot(pydantic_xml.BaseXmlModel, tag='disk', search_mode='unordered'):
	name: typing.Union[typing.Union[typing.Annotated[str, pydantic.Field(pattern='(ioemu:)?(fd|hd|sd|vd|xvd|ubd)[a-zA-Z0-9_]+')], typing.Annotated[str, pydantic.Field(pattern='nvme[0-9]+n[0-9]+(p[0-9]+)?')]], typing.Annotated[str, pydantic.Field(pattern='(/|[a-zA-Z]:\\\\).+')]] = pydantic_xml.attr(name='name')
	snapshot: typing.Optional[typing.Literal['no', 'internal', 'external', 'manual']] = pydantic_xml.attr(name='snapshot', default=None)
	type: typing.Optional[typing.Literal['file', 'block', 'network']] = pydantic_xml.attr(name='type', default=None)
	source: typing.Optional[_disksnapshot_Variant_source] = pydantic_xml.element(tag='source', default=None)
	driver: typing.Optional[_driver] = pydantic_xml.element(tag='driver', default=None)
	snapshot_delete_in_progress: typing.Optional[_snapshot_delete_in_progress] = pydantic_xml.element(tag='snapshotDeleteInProgress', default=None)

_disksnapshot = disksnapshot

class disks(pydantic_xml.BaseXmlModel, tag='disks', search_mode='unordered'):
	disk_list: typing.Optional[typing.List[_disksnapshot]] = pydantic_xml.element(tag='disk', default=None)

_disks = disks

class revert_disks(pydantic_xml.BaseXmlModel, tag='revertDisks', search_mode='unordered'):
	disk_list: typing.Optional[typing.List[_disksnapshot]] = pydantic_xml.element(tag='disk', default=None)

_revert_disks = revert_disks

class active(pydantic_xml.BaseXmlModel, tag='active', search_mode='unordered'):
	value: typing.Literal['0', '1']

_active = active

class uuid(pydantic_xml.BaseXmlModel, tag='uuid', search_mode='unordered'):
	value: typing.Union[typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{32}')], typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{8}\\-([a-fA-F0-9]{4}\\-){3}[a-fA-F0-9]{12}')]]

_uuid = uuid

class domain(pydantic_xml.BaseXmlModel, tag='domain', search_mode='strict'):
	uuid: _uuid = pydantic_xml.element(tag='uuid')

_domain = domain

class parent(pydantic_xml.BaseXmlModel, tag='parent', search_mode='strict'):
	name: _name = pydantic_xml.element(tag='name')

_parent = parent

class custom_element(pydantic_xml.BaseXmlModel, tag='*', search_mode='strict'):
	pass

_custom_element = custom_element

class domainsnapshot_cookie(pydantic_xml.BaseXmlModel, tag='cookie', search_mode='unordered'):
	custom_element_list: typing.Optional[typing.List[_custom_element]] = pydantic_xml.element(default=None)

_domainsnapshot_cookie = domainsnapshot_cookie

class domainsnapshot(pydantic_xml.BaseXmlModel, tag='domainsnapshot', search_mode='unordered'):
	name: typing.Optional[_name] = pydantic_xml.element(tag='name', default=None)
	description: typing.Optional[_description] = pydantic_xml.element(tag='description', default=None)
	state: typing.Optional[_state] = pydantic_xml.element(tag='state', default=None)
	creation_time: typing.Optional[_creation_time] = pydantic_xml.element(tag='creationTime', default=None)
	memory: typing.Optional[_memory] = pydantic_xml.element(tag='memory', default=None)
	disks: typing.Optional[_disks] = pydantic_xml.element(tag='disks', default=None)
	revert_disks: typing.Optional[_revert_disks] = pydantic_xml.element(tag='revertDisks', default=None)
	active: typing.Optional[_active] = pydantic_xml.element(tag='active', default=None)
	domain: typing.Optional[_domain] = pydantic_xml.element(tag='domain', default=None)
	parent: typing.Optional[_parent] = pydantic_xml.element(tag='parent', default=None)
	cookie: typing.Optional[_domainsnapshot_cookie] = pydantic_xml.element(tag='cookie', default=None)

_domainsnapshot = domainsnapshot

domainsnapshot = _domainsnapshot

