import typing
import pydantic
import pydantic_xml

# This file was automatically generated by relaxng-to-pydantic. Do not modify.
class incremental(pydantic_xml.BaseXmlModel, tag='incremental', search_mode='strict'):
	value: str

_incremental = incremental

class label(pydantic_xml.BaseXmlModel, tag='label', search_mode='strict'):
	value: str

_label = label

class dev_seclabel(pydantic_xml.BaseXmlModel, tag='seclabel', search_mode='unordered'):
	model: typing.Optional[str] = pydantic_xml.attr(name='model', default=None)
	relabel: typing.Optional[typing.Literal['no', 'yes']] = pydantic_xml.attr(name='relabel', default=None)
	labelskip: typing.Optional[typing.Literal['yes']] = pydantic_xml.attr(name='labelskip', default=None)
	label_list: typing.Optional[typing.List[_label]] = pydantic_xml.element(tag='label', default=None)

_dev_seclabel = dev_seclabel

class secret(pydantic_xml.BaseXmlModel, tag='secret', search_mode='unordered'):
	type: typing.Literal['passphrase'] = pydantic_xml.attr(name='type')
	uuid: typing.Optional[typing.Union[typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{32}')], typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{8}\\-([a-fA-F0-9]{4}\\-){3}[a-fA-F0-9]{12}')]]] = pydantic_xml.attr(name='uuid', default=None)
	usage: typing.Optional[str] = pydantic_xml.attr(name='usage', default=None)

_secret = secret

class cipher(pydantic_xml.BaseXmlModel, tag='cipher', search_mode='strict'):
	name: str = pydantic_xml.attr(name='name')
	size: int = pydantic_xml.attr(name='size')
	mode: typing.Optional[str] = pydantic_xml.attr(name='mode', default=None)
	hash: typing.Optional[str] = pydantic_xml.attr(name='hash', default=None)

_cipher = cipher

class ivgen(pydantic_xml.BaseXmlModel, tag='ivgen', search_mode='strict'):
	name: str = pydantic_xml.attr(name='name')
	hash: typing.Optional[str] = pydantic_xml.attr(name='hash', default=None)

_ivgen = ivgen

class backup_encryption(pydantic_xml.BaseXmlModel, tag='encryption', search_mode='unordered'):
	format: typing.Literal['luks'] = pydantic_xml.attr(name='format')
	engine: typing.Optional[typing.Literal['qemu']] = pydantic_xml.attr(name='engine', default=None)
	secret: _secret = pydantic_xml.element(tag='secret')
	cipher: typing.Optional[_cipher] = pydantic_xml.element(tag='cipher', default=None)
	ivgen: typing.Optional[_ivgen] = pydantic_xml.element(tag='ivgen', default=None)

_backup_encryption = backup_encryption

class backup_push_driver(pydantic_xml.BaseXmlModel, tag='driver', search_mode='strict'):
	type: typing.Literal['raw', 'dir', 'bochs', 'cloop', 'dmg', 'iso', 'vpc', 'vdi', 'fat', 'vhd', 'ploop', 'luks', 'cow', 'qcow', 'qcow2', 'qed', 'vmdk'] = pydantic_xml.attr(name='type')

_backup_push_driver = backup_push_driver

class disk_target(pydantic_xml.BaseXmlModel, tag='target', search_mode='unordered'):
	file: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='(/|[a-zA-Z]:\\\\).+')]] = pydantic_xml.attr(name='file', default=None)
	seclabel_list: typing.Optional[typing.List[_dev_seclabel]] = pydantic_xml.element(tag='seclabel', default=None)
	encryption: typing.Optional[_backup_encryption] = pydantic_xml.element(tag='encryption', default=None)
	dev: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='(/|[a-zA-Z]:\\\\).+')]] = pydantic_xml.attr(name='dev', default=None)

_disk_target = disk_target

class disks_disk(pydantic_xml.BaseXmlModel, tag='disk', search_mode='unordered'):
	model_config = {'extra': 'forbid'}
	name: typing.Union[typing.Annotated[str, pydantic.Field(pattern='(ioemu:)?(fd|hd|sd|vd|xvd|ubd)[a-zA-Z0-9_]+')], typing.Annotated[str, pydantic.Field(pattern='nvme[0-9]+n[0-9]+(p[0-9]+)?')]] = pydantic_xml.attr(name='name')
	backupmode: typing.Optional[typing.Literal['full', 'incremental']] = pydantic_xml.attr(name='backupmode', default=None)
	incremental: typing.Optional[str] = pydantic_xml.attr(name='incremental', default=None)
	backup: typing.Optional[typing.Literal['no', 'yes']] = pydantic_xml.attr(name='backup', default=None)
	type: typing.Optional[typing.Literal['file', 'block']] = pydantic_xml.attr(name='type', default=None)
	target: typing.Optional[_disk_target] = pydantic_xml.element(tag='target', default=None)
	driver: typing.Optional[_backup_push_driver] = pydantic_xml.element(tag='driver', default=None)

_disks_disk = disks_disk

class server(pydantic_xml.BaseXmlModel, tag='server', search_mode='unordered'):
	tls: typing.Optional[typing.Literal['yes', 'no']] = pydantic_xml.attr(name='tls', default=None)
	transport: typing.Optional[typing.Literal['tcp', 'unix', 'fd']] = pydantic_xml.attr(name='transport', default=None)
	name: typing.Optional[typing.Union[typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9\\.\\-]+')], typing.Union[typing.Annotated[str, pydantic.Field(pattern='(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))')], typing.Annotated[str, pydantic.Field(pattern='(([0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){6}:[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){5}:([0-9A-Fa-f]{1,4}:)?[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){4}:([0-9A-Fa-f]{1,4}:){0,2}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){3}:([0-9A-Fa-f]{1,4}:){0,3}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){2}:([0-9A-Fa-f]{1,4}:){0,4}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){6}(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|(([0-9A-Fa-f]{1,4}:){0,5}:(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|(::([0-9A-Fa-f]{1,4}:){0,5}(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|([0-9A-Fa-f]{1,4}::([0-9A-Fa-f]{1,4}:){0,5}[0-9A-Fa-f]{1,4})|(::([0-9A-Fa-f]{1,4}:){0,6}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){1,7}:)|(::)')]]]] = pydantic_xml.attr(name='name', default=None)
	port: typing.Optional[int] = pydantic_xml.attr(name='port', default=None)
	socket: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='(/|[a-zA-Z]:\\\\).+')]] = pydantic_xml.attr(name='socket', default=None)
	fdgroup: typing.Optional[str] = pydantic_xml.attr(name='fdgroup', default=None)

_server = server

class backup_pull_driver(pydantic_xml.BaseXmlModel, tag='driver', search_mode='strict'):
	type: typing.Literal['qcow2'] = pydantic_xml.attr(name='type')

_backup_pull_driver = backup_pull_driver

class disk_scratch(pydantic_xml.BaseXmlModel, tag='scratch', search_mode='unordered'):
	file: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='(/|[a-zA-Z]:\\\\).+')]] = pydantic_xml.attr(name='file', default=None)
	seclabel_list: typing.Optional[typing.List[_dev_seclabel]] = pydantic_xml.element(tag='seclabel', default=None)
	encryption: typing.Optional[_backup_encryption] = pydantic_xml.element(tag='encryption', default=None)
	dev: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='(/|[a-zA-Z]:\\\\).+')]] = pydantic_xml.attr(name='dev', default=None)

_disk_scratch = disk_scratch

class backup_disks_pull_disks_disk(pydantic_xml.BaseXmlModel, tag='disk', search_mode='unordered'):
	model_config = {'extra': 'forbid'}
	name: typing.Union[typing.Annotated[str, pydantic.Field(pattern='(ioemu:)?(fd|hd|sd|vd|xvd|ubd)[a-zA-Z0-9_]+')], typing.Annotated[str, pydantic.Field(pattern='nvme[0-9]+n[0-9]+(p[0-9]+)?')]] = pydantic_xml.attr(name='name')
	backupmode: typing.Optional[typing.Literal['full', 'incremental']] = pydantic_xml.attr(name='backupmode', default=None)
	incremental: typing.Optional[str] = pydantic_xml.attr(name='incremental', default=None)
	exportname: typing.Optional[str] = pydantic_xml.attr(name='exportname', default=None)
	exportbitmap: typing.Optional[str] = pydantic_xml.attr(name='exportbitmap', default=None)
	backup: typing.Optional[typing.Literal['no', 'yes']] = pydantic_xml.attr(name='backup', default=None)
	type: typing.Optional[typing.Literal['file', 'block']] = pydantic_xml.attr(name='type', default=None)
	scratch: typing.Optional[_disk_scratch] = pydantic_xml.element(tag='scratch', default=None)
	driver: typing.Optional[_backup_pull_driver] = pydantic_xml.element(tag='driver', default=None)

_backup_disks_pull_disks_disk = backup_disks_pull_disks_disk

class domainbackup_disks(pydantic_xml.BaseXmlModel, tag='disks', search_mode='unordered'):
	disk_list: typing.List[typing.Union[_disks_disk, _backup_disks_pull_disks_disk]] = pydantic_xml.element(tag='disk', min_length=1)

_domainbackup_disks = domainbackup_disks

class domainbackup(pydantic_xml.BaseXmlModel, tag='domainbackup', search_mode='unordered'):
	incremental: typing.Optional[_incremental] = pydantic_xml.element(tag='incremental', default=None)
	mode: typing.Optional[typing.Literal['push', 'pull']] = pydantic_xml.attr(name='mode', default=None)
	disks: typing.Optional[_domainbackup_disks] = pydantic_xml.element(tag='disks', default=None)
	server: typing.Optional[_server] = pydantic_xml.element(tag='server', default=None)

_domainbackup = domainbackup

domainbackup = _domainbackup

