import typing
import pydantic
import pydantic_xml

# This file was automatically generated by relaxng-to-pydantic. Do not modify.
class path(pydantic_xml.BaseXmlModel, tag='path', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='(/|[a-zA-Z]:\\\\).+')]

_path = path

class domain(pydantic_xml.BaseXmlModel, tag='domain', search_mode='strict'):
	value: str

_domain = domain

class machine(pydantic_xml.BaseXmlModel, tag='machine', search_mode='strict'):
	value: str

_machine = machine

class arch(pydantic_xml.BaseXmlModel, tag='arch', search_mode='strict'):
	value: str

_arch = arch

class vcpu(pydantic_xml.BaseXmlModel, tag='vcpu', search_mode='strict'):
	max: int = pydantic_xml.attr(name='max')

_vcpu = vcpu

class iothreads(pydantic_xml.BaseXmlModel, tag='iothreads', search_mode='strict'):
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')

_iothreads = iothreads

class value(pydantic_xml.BaseXmlModel, tag='value', search_mode='strict'):
	value: str

_value = value

class enum(pydantic_xml.BaseXmlModel, tag='enum', search_mode='unordered'):
	name: str = pydantic_xml.attr(name='name')
	value_list: typing.Optional[typing.List[_value]] = pydantic_xml.element(tag='value', default=None)

_enum = enum

class loader(pydantic_xml.BaseXmlModel, tag='loader', search_mode='unordered'):
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')
	value_list: typing.Optional[typing.List[_value]] = pydantic_xml.element(tag='value', default=None)
	enum_list: typing.Optional[typing.List[_enum]] = pydantic_xml.element(tag='enum', default=None)

_loader = loader

class os(pydantic_xml.BaseXmlModel, tag='os', search_mode='unordered'):
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')
	enum_list: typing.Optional[typing.List[_enum]] = pydantic_xml.element(tag='enum', default=None)
	loader: typing.Optional[_loader] = pydantic_xml.element(tag='loader', default=None)

_os = os

class cpu_host(pydantic_xml.BaseXmlModel, tag='mode', search_mode='unordered'):
	name: typing.Literal['host-passthrough'] = pydantic_xml.attr(name='name')
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')
	enum_list: typing.Optional[typing.List[_enum]] = pydantic_xml.element(tag='enum', default=None)

_cpu_host = cpu_host

class cpu_max(pydantic_xml.BaseXmlModel, tag='mode', search_mode='unordered'):
	name: typing.Literal['maximum'] = pydantic_xml.attr(name='name')
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')
	enum_list: typing.Optional[typing.List[_enum]] = pydantic_xml.element(tag='enum', default=None)

_cpu_max = cpu_max

class cpu_model(pydantic_xml.BaseXmlModel, tag='model', search_mode='unordered'):
	value: typing.Optional[str] = None
	fallback: typing.Optional[typing.Literal['allow', 'forbid']] = pydantic_xml.attr(name='fallback', default=None)
	vendor_id: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='[^,]{12}')]] = pydantic_xml.attr(name='vendor_id', default=None)

_cpu_model = cpu_model

class cpu_vendor(pydantic_xml.BaseXmlModel, tag='vendor', search_mode='strict'):
	value: str

_cpu_vendor = cpu_vendor

class cpu_max_phys_addr(pydantic_xml.BaseXmlModel, tag='maxphysaddr', search_mode='strict'):
	mode: typing.Literal['emulate', 'passthrough'] = pydantic_xml.attr(name='mode')
	bits: typing.Optional[int] = pydantic_xml.attr(name='bits', default=None)
	limit: typing.Optional[int] = pydantic_xml.attr(name='limit', default=None)

_cpu_max_phys_addr = cpu_max_phys_addr

class cpu_feature(pydantic_xml.BaseXmlModel, tag='feature', search_mode='strict'):
	policy: typing.Literal['force', 'require', 'optional', 'disable', 'forbid'] = pydantic_xml.attr(name='policy')
	name: typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9\\-_\\.]+')] = pydantic_xml.attr(name='name')

_cpu_feature = cpu_feature

class cpu_host_model(pydantic_xml.BaseXmlModel, tag='mode', search_mode='unordered'):
	name: typing.Literal['host-model'] = pydantic_xml.attr(name='name')
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')
	model: typing.Optional[_cpu_model] = pydantic_xml.element(tag='model', default=None)
	vendor: typing.Optional[_cpu_vendor] = pydantic_xml.element(tag='vendor', default=None)
	maxphysaddr: typing.Optional[_cpu_max_phys_addr] = pydantic_xml.element(tag='maxphysaddr', default=None)
	feature_list: typing.Optional[typing.List[_cpu_feature]] = pydantic_xml.element(tag='feature', default=None)

_cpu_host_model = cpu_host_model

class model(pydantic_xml.BaseXmlModel, tag='model', search_mode='strict'):
	value: str
	usable: typing.Literal['yes', 'no', 'unknown'] = pydantic_xml.attr(name='usable')
	deprecated: typing.Optional[typing.Literal['yes', 'no']] = pydantic_xml.attr(name='deprecated', default=None)
	canonical: typing.Optional[str] = pydantic_xml.attr(name='canonical', default=None)
	vendor: str = pydantic_xml.attr(name='vendor')

_model = model

class feature(pydantic_xml.BaseXmlModel, tag='feature', search_mode='strict'):
	name: str = pydantic_xml.attr(name='name')

_feature = feature

class blockers(pydantic_xml.BaseXmlModel, tag='blockers', search_mode='unordered'):
	model: str = pydantic_xml.attr(name='model')
	feature_list: typing.List[_feature] = pydantic_xml.element(tag='feature', min_length=1)

_blockers = blockers

class cpu_custom(pydantic_xml.BaseXmlModel, tag='mode', search_mode='unordered'):
	name: typing.Literal['custom'] = pydantic_xml.attr(name='name')
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')
	model_list: typing.Optional[typing.List[_model]] = pydantic_xml.element(tag='model', default=None)
	blockers_list: typing.Optional[typing.List[_blockers]] = pydantic_xml.element(tag='blockers', default=None)

_cpu_custom = cpu_custom

class cpu(pydantic_xml.BaseXmlModel, tag='cpu', search_mode='strict'):
	mode: _cpu_host = pydantic_xml.element(tag='mode')
	mode2: _cpu_max = pydantic_xml.element(tag='mode')
	mode3: _cpu_host_model = pydantic_xml.element(tag='mode')
	mode4: _cpu_custom = pydantic_xml.element(tag='mode')

_cpu = cpu

class memory_backing(pydantic_xml.BaseXmlModel, tag='memoryBacking', search_mode='unordered'):
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')
	enum_list: typing.Optional[typing.List[_enum]] = pydantic_xml.element(tag='enum', default=None)

_memory_backing = memory_backing

class disk(pydantic_xml.BaseXmlModel, tag='disk', search_mode='unordered'):
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')
	enum_list: typing.Optional[typing.List[_enum]] = pydantic_xml.element(tag='enum', default=None)

_disk = disk

class graphics(pydantic_xml.BaseXmlModel, tag='graphics', search_mode='unordered'):
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')
	enum_list: typing.Optional[typing.List[_enum]] = pydantic_xml.element(tag='enum', default=None)

_graphics = graphics

class video(pydantic_xml.BaseXmlModel, tag='video', search_mode='unordered'):
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')
	enum_list: typing.Optional[typing.List[_enum]] = pydantic_xml.element(tag='enum', default=None)

_video = video

class hostdev(pydantic_xml.BaseXmlModel, tag='hostdev', search_mode='unordered'):
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')
	enum_list: typing.Optional[typing.List[_enum]] = pydantic_xml.element(tag='enum', default=None)

_hostdev = hostdev

class rng(pydantic_xml.BaseXmlModel, tag='rng', search_mode='unordered'):
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')
	enum_list: typing.Optional[typing.List[_enum]] = pydantic_xml.element(tag='enum', default=None)

_rng = rng

class filesystem(pydantic_xml.BaseXmlModel, tag='filesystem', search_mode='unordered'):
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')
	enum_list: typing.Optional[typing.List[_enum]] = pydantic_xml.element(tag='enum', default=None)

_filesystem = filesystem

class tpm(pydantic_xml.BaseXmlModel, tag='tpm', search_mode='unordered'):
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')
	enum_list: typing.Optional[typing.List[_enum]] = pydantic_xml.element(tag='enum', default=None)

_tpm = tpm

class redirdev(pydantic_xml.BaseXmlModel, tag='redirdev', search_mode='unordered'):
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')
	enum_list: typing.Optional[typing.List[_enum]] = pydantic_xml.element(tag='enum', default=None)

_redirdev = redirdev

class channel(pydantic_xml.BaseXmlModel, tag='channel', search_mode='unordered'):
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')
	enum_list: typing.Optional[typing.List[_enum]] = pydantic_xml.element(tag='enum', default=None)

_channel = channel

class crypto(pydantic_xml.BaseXmlModel, tag='crypto', search_mode='unordered'):
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')
	enum_list: typing.Optional[typing.List[_enum]] = pydantic_xml.element(tag='enum', default=None)

_crypto = crypto

class interface(pydantic_xml.BaseXmlModel, tag='interface', search_mode='unordered'):
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')
	enum_list: typing.Optional[typing.List[_enum]] = pydantic_xml.element(tag='enum', default=None)

_interface = interface

class panic(pydantic_xml.BaseXmlModel, tag='panic', search_mode='unordered'):
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')
	enum_list: typing.Optional[typing.List[_enum]] = pydantic_xml.element(tag='enum', default=None)

_panic = panic

class console(pydantic_xml.BaseXmlModel, tag='console', search_mode='unordered'):
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')
	enum_list: typing.Optional[typing.List[_enum]] = pydantic_xml.element(tag='enum', default=None)

_console = console

class devices(pydantic_xml.BaseXmlModel, tag='devices', search_mode='strict'):
	disk: typing.Optional[_disk] = pydantic_xml.element(tag='disk', default=None)
	graphics: typing.Optional[_graphics] = pydantic_xml.element(tag='graphics', default=None)
	video: typing.Optional[_video] = pydantic_xml.element(tag='video', default=None)
	hostdev: typing.Optional[_hostdev] = pydantic_xml.element(tag='hostdev', default=None)
	rng: typing.Optional[_rng] = pydantic_xml.element(tag='rng', default=None)
	filesystem: typing.Optional[_filesystem] = pydantic_xml.element(tag='filesystem', default=None)
	tpm: typing.Optional[_tpm] = pydantic_xml.element(tag='tpm', default=None)
	redirdev: typing.Optional[_redirdev] = pydantic_xml.element(tag='redirdev', default=None)
	channel: typing.Optional[_channel] = pydantic_xml.element(tag='channel', default=None)
	crypto: typing.Optional[_crypto] = pydantic_xml.element(tag='crypto', default=None)
	interface: typing.Optional[_interface] = pydantic_xml.element(tag='interface', default=None)
	panic: typing.Optional[_panic] = pydantic_xml.element(tag='panic', default=None)
	console: typing.Optional[_console] = pydantic_xml.element(tag='console', default=None)

_devices = devices

class gic(pydantic_xml.BaseXmlModel, tag='gic', search_mode='unordered'):
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')
	enum_list: typing.Optional[typing.List[_enum]] = pydantic_xml.element(tag='enum', default=None)

_gic = gic

class vmcoreinfo(pydantic_xml.BaseXmlModel, tag='vmcoreinfo', search_mode='strict'):
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')

_vmcoreinfo = vmcoreinfo

class vmgenid(pydantic_xml.BaseXmlModel, tag='genid', search_mode='strict'):
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')

_vmgenid = vmgenid

class backing_store_input(pydantic_xml.BaseXmlModel, tag='backingStoreInput', search_mode='strict'):
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')

_backing_store_input = backing_store_input

class backup(pydantic_xml.BaseXmlModel, tag='backup', search_mode='strict'):
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')

_backup = backup

class async_teardown(pydantic_xml.BaseXmlModel, tag='async-teardown', search_mode='strict'):
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')

_async_teardown = async_teardown

class s390_pv(pydantic_xml.BaseXmlModel, tag='s390-pv', search_mode='strict'):
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')

_s390_pv = s390_pv

class ps2(pydantic_xml.BaseXmlModel, tag='ps2', search_mode='strict'):
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')

_ps2 = ps2

class tdx(pydantic_xml.BaseXmlModel, tag='tdx', search_mode='strict'):
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')

_tdx = tdx

class cbitpos(pydantic_xml.BaseXmlModel, tag='cbitpos', search_mode='strict'):
	value: int

_cbitpos = cbitpos

class reduced_phys_bits(pydantic_xml.BaseXmlModel, tag='reducedPhysBits', search_mode='strict'):
	value: int

_reduced_phys_bits = reduced_phys_bits

class max_guests(pydantic_xml.BaseXmlModel, tag='maxGuests', search_mode='strict'):
	value: int

_max_guests = max_guests

class max_e_s_guests(pydantic_xml.BaseXmlModel, tag='maxESGuests', search_mode='strict'):
	value: int

_max_e_s_guests = max_e_s_guests

class cpu0_id(pydantic_xml.BaseXmlModel, tag='cpu0Id', search_mode='strict'):
	value: str

_cpu0_id = cpu0_id

class sev(pydantic_xml.BaseXmlModel, tag='sev', search_mode='strict'):
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')
	cbitpos: typing.Optional[_cbitpos] = pydantic_xml.element(tag='cbitpos', default=None)
	reduced_phys_bits: typing.Optional[_reduced_phys_bits] = pydantic_xml.element(tag='reducedPhysBits', default=None)
	max_guests: typing.Optional[_max_guests] = pydantic_xml.element(tag='maxGuests', default=None)
	max_e_s_guests: typing.Optional[_max_e_s_guests] = pydantic_xml.element(tag='maxESGuests', default=None)
	cpu0_id: typing.Optional[_cpu0_id] = pydantic_xml.element(tag='cpu0Id', default=None)

_sev = sev

class flc(pydantic_xml.BaseXmlModel, tag='flc', search_mode='unordered'):
	value: typing.Literal['yes', 'no']

_flc = flc

class sgx1(pydantic_xml.BaseXmlModel, tag='sgx1', search_mode='unordered'):
	value: typing.Literal['yes', 'no']

_sgx1 = sgx1

class sgx2(pydantic_xml.BaseXmlModel, tag='sgx2', search_mode='unordered'):
	value: typing.Literal['yes', 'no']

_sgx2 = sgx2

class section_size(pydantic_xml.BaseXmlModel, tag='section_size', search_mode='strict'):
	value: int
	unit: typing.Literal['KiB'] = pydantic_xml.attr(name='unit')

_section_size = section_size

class section(pydantic_xml.BaseXmlModel, tag='section', search_mode='strict'):
	node: int = pydantic_xml.attr(name='node')
	size: int = pydantic_xml.attr(name='size')
	unit: typing.Literal['KiB'] = pydantic_xml.attr(name='unit')

_section = section

class sections(pydantic_xml.BaseXmlModel, tag='sections', search_mode='unordered'):
	section_list: typing.Optional[typing.List[_section]] = pydantic_xml.element(tag='section', default=None)

_sections = sections

class sgx(pydantic_xml.BaseXmlModel, tag='sgx', search_mode='strict'):
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')
	flc: typing.Optional[_flc] = pydantic_xml.element(tag='flc', default=None)
	sgx1: typing.Optional[_sgx1] = pydantic_xml.element(tag='sgx1', default=None)
	sgx2: typing.Optional[_sgx2] = pydantic_xml.element(tag='sgx2', default=None)
	section_size: typing.Optional[_section_size] = pydantic_xml.element(tag='section_size', default=None)
	sections: typing.Optional[_sections] = pydantic_xml.element(tag='sections', default=None)

_sgx = sgx

class spinlocks(pydantic_xml.BaseXmlModel, tag='spinlocks', search_mode='strict'):
	value: int

_spinlocks = spinlocks

class stimer_direct(pydantic_xml.BaseXmlModel, tag='stimer_direct', search_mode='unordered'):
	value: typing.Literal['on', 'off']

_stimer_direct = stimer_direct

class tlbflush_direct(pydantic_xml.BaseXmlModel, tag='tlbflush_direct', search_mode='unordered'):
	value: typing.Literal['on', 'off']

_tlbflush_direct = tlbflush_direct

class tlbflush_extended(pydantic_xml.BaseXmlModel, tag='tlbflush_extended', search_mode='unordered'):
	value: typing.Literal['on', 'off']

_tlbflush_extended = tlbflush_extended

class vendor_id(pydantic_xml.BaseXmlModel, tag='vendor_id', search_mode='strict'):
	value: str

_vendor_id = vendor_id

class defaults(pydantic_xml.BaseXmlModel, tag='defaults', search_mode='strict'):
	spinlocks: typing.Optional[_spinlocks] = pydantic_xml.element(tag='spinlocks', default=None)
	stimer_direct: typing.Optional[_stimer_direct] = pydantic_xml.element(tag='stimer_direct', default=None)
	tlbflush_direct: typing.Optional[_tlbflush_direct] = pydantic_xml.element(tag='tlbflush_direct', default=None)
	tlbflush_extended: typing.Optional[_tlbflush_extended] = pydantic_xml.element(tag='tlbflush_extended', default=None)
	vendor_id: typing.Optional[_vendor_id] = pydantic_xml.element(tag='vendor_id', default=None)

_defaults = defaults

class hyperv(pydantic_xml.BaseXmlModel, tag='hyperv', search_mode='unordered'):
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')
	enum_list: typing.Optional[typing.List[_enum]] = pydantic_xml.element(tag='enum', default=None)
	defaults: typing.Optional[_defaults] = pydantic_xml.element(tag='defaults', default=None)

_hyperv = hyperv

class launch_security(pydantic_xml.BaseXmlModel, tag='launchSecurity', search_mode='unordered'):
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')
	enum_list: typing.Optional[typing.List[_enum]] = pydantic_xml.element(tag='enum', default=None)

_launch_security = launch_security

class features(pydantic_xml.BaseXmlModel, tag='features', search_mode='strict'):
	gic: typing.Optional[_gic] = pydantic_xml.element(tag='gic', default=None)
	vmcoreinfo: typing.Optional[_vmcoreinfo] = pydantic_xml.element(tag='vmcoreinfo', default=None)
	genid: typing.Optional[_vmgenid] = pydantic_xml.element(tag='genid', default=None)
	backing_store_input: typing.Optional[_backing_store_input] = pydantic_xml.element(tag='backingStoreInput', default=None)
	backup: typing.Optional[_backup] = pydantic_xml.element(tag='backup', default=None)
	async_teardown: typing.Optional[_async_teardown] = pydantic_xml.element(tag='async-teardown', default=None)
	s390_pv: typing.Optional[_s390_pv] = pydantic_xml.element(tag='s390-pv', default=None)
	ps2: typing.Optional[_ps2] = pydantic_xml.element(tag='ps2', default=None)
	tdx: typing.Optional[_tdx] = pydantic_xml.element(tag='tdx', default=None)
	sev: typing.Optional[_sev] = pydantic_xml.element(tag='sev', default=None)
	sgx: typing.Optional[_sgx] = pydantic_xml.element(tag='sgx', default=None)
	hyperv: typing.Optional[_hyperv] = pydantic_xml.element(tag='hyperv', default=None)
	launch_security: typing.Optional[_launch_security] = pydantic_xml.element(tag='launchSecurity', default=None)

_features = features

class domain_capabilities(pydantic_xml.BaseXmlModel, tag='domainCapabilities', search_mode='unordered'):
	path: typing.Optional[_path] = pydantic_xml.element(tag='path', default=None)
	domain: _domain = pydantic_xml.element(tag='domain')
	machine: typing.Optional[_machine] = pydantic_xml.element(tag='machine', default=None)
	arch: _arch = pydantic_xml.element(tag='arch')
	vcpu: typing.Optional[_vcpu] = pydantic_xml.element(tag='vcpu', default=None)
	iothreads: typing.Optional[_iothreads] = pydantic_xml.element(tag='iothreads', default=None)
	os: typing.Optional[_os] = pydantic_xml.element(tag='os', default=None)
	cpu: typing.Optional[_cpu] = pydantic_xml.element(tag='cpu', default=None)
	memory_backing: typing.Optional[_memory_backing] = pydantic_xml.element(tag='memoryBacking', default=None)
	devices: typing.Optional[_devices] = pydantic_xml.element(tag='devices', default=None)
	features: typing.Optional[_features] = pydantic_xml.element(tag='features', default=None)

_domain_capabilities = domain_capabilities

domaincaps = _domain_capabilities

