import typing
import pydantic
import pydantic_xml

# This file was automatically generated by relaxng-to-pydantic. Do not modify.
class name(pydantic_xml.BaseXmlModel, tag='name', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9_\\-][a-zA-Z0-9_\\-.]*')]

_name = name

class description(pydantic_xml.BaseXmlModel, tag='description', search_mode='strict'):
	value: str

_description = description

class creation_time(pydantic_xml.BaseXmlModel, tag='creationTime', search_mode='strict'):
	value: int

_creation_time = creation_time

class diskcheckpoint(pydantic_xml.BaseXmlModel, tag='disk', search_mode='unordered'):
	name: typing.Union[typing.Union[typing.Annotated[str, pydantic.Field(pattern='(ioemu:)?(fd|hd|sd|vd|xvd|ubd)[a-zA-Z0-9_]+')], typing.Annotated[str, pydantic.Field(pattern='nvme[0-9]+n[0-9]+(p[0-9]+)?')]], typing.Annotated[str, pydantic.Field(pattern='(/|[a-zA-Z]:\\\\).+')]] = pydantic_xml.attr(name='name')
	checkpoint: typing.Optional[typing.Literal['no', 'bitmap']] = pydantic_xml.attr(name='checkpoint', default=None)
	bitmap: typing.Optional[str] = pydantic_xml.attr(name='bitmap', default=None)
	size: typing.Optional[int] = pydantic_xml.attr(name='size', default=None)

_diskcheckpoint = diskcheckpoint

class disks(pydantic_xml.BaseXmlModel, tag='disks', search_mode='unordered'):
	disk_list: typing.List[_diskcheckpoint] = pydantic_xml.element(tag='disk', min_length=1)

_disks = disks

class parent(pydantic_xml.BaseXmlModel, tag='parent', search_mode='strict'):
	name: _name = pydantic_xml.element(tag='name')

_parent = parent

class domaincheckpoint(pydantic_xml.BaseXmlModel, tag='domaincheckpoint', search_mode='unordered'):
	name: typing.Optional[_name] = pydantic_xml.element(tag='name', default=None)
	description: typing.Optional[_description] = pydantic_xml.element(tag='description', default=None)
	creation_time: typing.Optional[_creation_time] = pydantic_xml.element(tag='creationTime', default=None)
	disks: typing.Optional[_disks] = pydantic_xml.element(tag='disks', default=None)
	parent: typing.Optional[_parent] = pydantic_xml.element(tag='parent', default=None)

_domaincheckpoint = domaincheckpoint

domaincheckpoint = _domaincheckpoint

