import typing
import pydantic
import pydantic_xml

# This file was automatically generated by relaxng-to-pydantic. Do not modify.
class name(pydantic_xml.BaseXmlModel, tag='name', search_mode='strict'):
	value: str

_name = name

class title(pydantic_xml.BaseXmlModel, tag='title', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='[^\\n]+')]

_title = title

class description(pydantic_xml.BaseXmlModel, tag='description', search_mode='strict'):
	value: str

_description = description

class custom_element(pydantic_xml.BaseXmlModel, tag='*', search_mode='strict'):
	pass

_custom_element = custom_element

class metadata(pydantic_xml.BaseXmlModel, tag='metadata', search_mode='unordered'):
	custom_element_list: typing.Optional[typing.List[_custom_element]] = pydantic_xml.element(default=None)

_metadata = metadata

class uuid(pydantic_xml.BaseXmlModel, tag='uuid', search_mode='unordered'):
	value: typing.Union[typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{32}')], typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{8}\\-([a-fA-F0-9]{4}\\-){3}[a-fA-F0-9]{12}')]]

_uuid = uuid

class bridge(pydantic_xml.BaseXmlModel, tag='bridge', search_mode='strict'):
	name: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9_\\.\\-\\\\:/]+')]] = pydantic_xml.attr(name='name', default=None)
	zone: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9_\\-]+')]] = pydantic_xml.attr(name='zone', default=None)
	stp: typing.Optional[typing.Literal['on', 'off']] = pydantic_xml.attr(name='stp', default=None)
	delay: typing.Optional[int] = pydantic_xml.attr(name='delay', default=None)
	mac_table_manager: typing.Optional[typing.Literal['kernel', 'libvirt']] = pydantic_xml.attr(name='macTableManager', default=None)

_bridge = bridge

class mtu(pydantic_xml.BaseXmlModel, tag='mtu', search_mode='strict'):
	size: int = pydantic_xml.attr(name='size')

_mtu = mtu

class mac(pydantic_xml.BaseXmlModel, tag='mac', search_mode='strict'):
	address: typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9][02468aAcCeE](:[a-fA-F0-9]{2}){5}')] = pydantic_xml.attr(name='address')

_mac = mac

class interface(pydantic_xml.BaseXmlModel, tag='interface', search_mode='strict'):
	dev: typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9_\\.\\-\\\\:/]+')] = pydantic_xml.attr(name='dev')
	connections: typing.Optional[int] = pydantic_xml.attr(name='connections', default=None)

_interface = interface

class Variant_address(pydantic_xml.BaseXmlModel, tag='address', search_mode='strict'):
	type: typing.Literal['pci'] = pydantic_xml.attr(name='type')
	domain: typing.Optional[typing.Annotated[int, pydantic.BeforeValidator(lambda v: (int(v) if v.isdigit() else int(v, 16)) if isinstance(v, str) else v)]] = pydantic_xml.attr(name='domain', default=None)
	bus: typing.Optional[typing.Annotated[int, pydantic.BeforeValidator(lambda v: (int(v) if v.isdigit() else int(v, 16)) if isinstance(v, str) else v)]] = pydantic_xml.attr(name='bus', default=None)
	slot: typing.Optional[typing.Annotated[int, pydantic.BeforeValidator(lambda v: (int(v) if v.isdigit() else int(v, 16)) if isinstance(v, str) else v)]] = pydantic_xml.attr(name='slot', default=None)
	function: typing.Optional[typing.Annotated[int, pydantic.BeforeValidator(lambda v: (int(v) if v.isdigit() else int(v, 16)) if isinstance(v, str) else v)]] = pydantic_xml.attr(name='function', default=None)
	multifunction: typing.Optional[typing.Literal['on', 'off']] = pydantic_xml.attr(name='multifunction', default=None)
	connections: typing.Optional[int] = pydantic_xml.attr(name='connections', default=None)

_Variant_address = Variant_address

class pf(pydantic_xml.BaseXmlModel, tag='pf', search_mode='strict'):
	dev: typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9_\\.\\-\\\\:/]+')] = pydantic_xml.attr(name='dev')

_pf = pf

class hostdev_driver(pydantic_xml.BaseXmlModel, tag='driver', search_mode='strict'):
	name: typing.Optional[typing.Literal['kvm', 'vfio', 'xen']] = pydantic_xml.attr(name='name', default=None)
	model: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9_\\+\\-]+')]] = pydantic_xml.attr(name='model', default=None)

_hostdev_driver = hostdev_driver

class nat_address(pydantic_xml.BaseXmlModel, tag='address', search_mode='strict'):
	start: typing.Annotated[str, pydantic.Field(pattern='(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))')] = pydantic_xml.attr(name='start')
	end: typing.Annotated[str, pydantic.Field(pattern='(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))')] = pydantic_xml.attr(name='end')

_nat_address = nat_address

class port(pydantic_xml.BaseXmlModel, tag='port', search_mode='strict'):
	start: int = pydantic_xml.attr(name='start')
	end: int = pydantic_xml.attr(name='end')

_port = port

class nat(pydantic_xml.BaseXmlModel, tag='nat', search_mode='unordered'):
	ipv6: typing.Optional[typing.Literal['yes', 'no']] = pydantic_xml.attr(name='ipv6', default=None)
	address: typing.Optional[_nat_address] = pydantic_xml.element(tag='address', default=None)
	port: typing.Optional[_port] = pydantic_xml.element(tag='port', default=None)

_nat = nat

class forward(pydantic_xml.BaseXmlModel, tag='forward', search_mode='unordered'):
	dev: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9_\\.\\-\\\\:/]+')]] = pydantic_xml.attr(name='dev', default=None)
	mode: typing.Optional[typing.Literal['nat', 'route', 'open', 'bridge', 'passthrough', 'private', 'vepa', 'hostdev']] = pydantic_xml.attr(name='mode', default=None)
	managed: typing.Optional[typing.Literal['yes', 'no']] = pydantic_xml.attr(name='managed', default=None)
	interface_list: typing.Optional[typing.List[_interface]] = pydantic_xml.element(tag='interface', default=None)
	address_list: typing.Optional[typing.List[_Variant_address]] = pydantic_xml.element(tag='address', default=None)
	pf: typing.Optional[_pf] = pydantic_xml.element(tag='pf', default=None)
	driver: typing.Optional[_hostdev_driver] = pydantic_xml.element(tag='driver', default=None)
	nat: typing.Optional[_nat] = pydantic_xml.element(tag='nat', default=None)

_forward = forward

class virtualport_parameters(pydantic_xml.BaseXmlModel, tag='parameters', search_mode='unordered'):
	managerid: typing.Optional[typing.Annotated[int, pydantic.BeforeValidator(lambda v: (int(v) if v.isdigit() else int(v, 16)) if isinstance(v, str) else v)]] = pydantic_xml.attr(name='managerid', default=None)
	typeid: typing.Optional[typing.Annotated[int, pydantic.BeforeValidator(lambda v: (int(v) if v.isdigit() else int(v, 16)) if isinstance(v, str) else v)]] = pydantic_xml.attr(name='typeid', default=None)
	typeidversion: typing.Optional[typing.Annotated[int, pydantic.BeforeValidator(lambda v: (int(v) if v.isdigit() else int(v, 16)) if isinstance(v, str) else v)]] = pydantic_xml.attr(name='typeidversion', default=None)
	instanceid: typing.Optional[typing.Union[typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{32}')], typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{8}\\-([a-fA-F0-9]{4}\\-){3}[a-fA-F0-9]{12}')]]] = pydantic_xml.attr(name='instanceid', default=None)
	profileid: typing.Optional[str] = pydantic_xml.attr(name='profileid', default=None)
	interfaceid: typing.Optional[typing.Union[typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{32}')], typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{8}\\-([a-fA-F0-9]{4}\\-){3}[a-fA-F0-9]{12}')]]] = pydantic_xml.attr(name='interfaceid', default=None)

_virtualport_parameters = virtualport_parameters

class virtualport(pydantic_xml.BaseXmlModel, tag='virtualport', search_mode='unordered'):
	type: typing.Optional[typing.Literal['802.1Qbg', '802.1Qbh', 'openvswitch', 'midonet']] = pydantic_xml.attr(name='type', default=None)
	parameters: typing.Optional[_virtualport_parameters] = pydantic_xml.element(tag='parameters', default=None)

_virtualport = virtualport

class inbound(pydantic_xml.BaseXmlModel, tag='inbound', search_mode='strict'):
	average: typing.Optional[int] = pydantic_xml.attr(name='average', default=None)
	peak: typing.Optional[int] = pydantic_xml.attr(name='peak', default=None)
	floor: typing.Optional[int] = pydantic_xml.attr(name='floor', default=None)
	burst: typing.Optional[int] = pydantic_xml.attr(name='burst', default=None)

_inbound = inbound

class outbound(pydantic_xml.BaseXmlModel, tag='outbound', search_mode='strict'):
	average: typing.Optional[int] = pydantic_xml.attr(name='average', default=None)
	peak: typing.Optional[int] = pydantic_xml.attr(name='peak', default=None)
	floor: typing.Optional[int] = pydantic_xml.attr(name='floor', default=None)
	burst: typing.Optional[int] = pydantic_xml.attr(name='burst', default=None)

_outbound = outbound

class bandwidth(pydantic_xml.BaseXmlModel, tag='bandwidth', search_mode='unordered'):
	class_i_d: typing.Optional[int] = pydantic_xml.attr(name='classID', default=None)
	inbound: typing.Optional[_inbound] = pydantic_xml.element(tag='inbound', default=None)
	outbound: typing.Optional[_outbound] = pydantic_xml.element(tag='outbound', default=None)

_bandwidth = bandwidth

class tag(pydantic_xml.BaseXmlModel, tag='tag', search_mode='strict'):
	id: int = pydantic_xml.attr(name='id')
	native_mode: typing.Optional[typing.Literal['tagged', 'untagged']] = pydantic_xml.attr(name='nativeMode', default=None)

_tag = tag

class vlan(pydantic_xml.BaseXmlModel, tag='vlan', search_mode='unordered'):
	trunk: typing.Optional[typing.Literal['yes']] = pydantic_xml.attr(name='trunk', default=None)
	tag_list: typing.List[_tag] = pydantic_xml.element(tag='tag', min_length=1)

_vlan = vlan

class portgroup(pydantic_xml.BaseXmlModel, tag='portgroup', search_mode='unordered'):
	name: typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9_\\.\\-\\\\:/]+')] = pydantic_xml.attr(name='name')
	default: typing.Optional[typing.Literal['yes', 'no']] = pydantic_xml.attr(name='default', default=None)
	trust_guest_rx_filters: typing.Optional[typing.Literal['yes', 'no']] = pydantic_xml.attr(name='trustGuestRxFilters', default=None)
	virtualport: typing.Optional[_virtualport] = pydantic_xml.element(tag='virtualport', default=None)
	bandwidth: typing.Optional[_bandwidth] = pydantic_xml.element(tag='bandwidth', default=None)
	vlan: typing.Optional[_vlan] = pydantic_xml.element(tag='vlan', default=None)

_portgroup = portgroup

class domain(pydantic_xml.BaseXmlModel, tag='domain', search_mode='strict'):
	name: typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9\\.\\-]+')] = pydantic_xml.attr(name='name')
	local_only: typing.Optional[typing.Literal['yes', 'no']] = pydantic_xml.attr(name='localOnly', default=None)
	register_: typing.Optional[typing.Literal['yes', 'no']] = pydantic_xml.attr(name='register', default=None)

_domain = domain

class forwarder(pydantic_xml.BaseXmlModel, tag='forwarder', search_mode='strict'):
	addr: typing.Optional[typing.Union[typing.Annotated[str, pydantic.Field(pattern='(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))')], typing.Annotated[str, pydantic.Field(pattern='(([0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){6}:[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){5}:([0-9A-Fa-f]{1,4}:)?[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){4}:([0-9A-Fa-f]{1,4}:){0,2}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){3}:([0-9A-Fa-f]{1,4}:){0,3}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){2}:([0-9A-Fa-f]{1,4}:){0,4}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){6}(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|(([0-9A-Fa-f]{1,4}:){0,5}:(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|(::([0-9A-Fa-f]{1,4}:){0,5}(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|([0-9A-Fa-f]{1,4}::([0-9A-Fa-f]{1,4}:){0,5}[0-9A-Fa-f]{1,4})|(::([0-9A-Fa-f]{1,4}:){0,6}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){1,7}:)|(::)')]]] = pydantic_xml.attr(name='addr', default=None)
	domain: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9\\.\\-]+')]] = pydantic_xml.attr(name='domain', default=None)
	port: typing.Optional[int] = pydantic_xml.attr(name='port', default=None)

_forwarder = forwarder

class txt(pydantic_xml.BaseXmlModel, tag='txt', search_mode='strict'):
	name: typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9\\.\\-]+')] = pydantic_xml.attr(name='name')
	value: str = pydantic_xml.attr(name='value')

_txt = txt

class srv(pydantic_xml.BaseXmlModel, tag='srv', search_mode='strict'):
	service: str = pydantic_xml.attr(name='service')
	protocol: typing.Annotated[str, pydantic.Field(pattern='(tcp)|(udp)')] = pydantic_xml.attr(name='protocol')
	domain: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9\\.\\-]+')]] = pydantic_xml.attr(name='domain', default=None)
	target: typing.Optional[str] = pydantic_xml.attr(name='target', default=None)
	port: typing.Optional[int] = pydantic_xml.attr(name='port', default=None)
	priority: typing.Optional[int] = pydantic_xml.attr(name='priority', default=None)
	weight: typing.Optional[int] = pydantic_xml.attr(name='weight', default=None)

_srv = srv

class hostname(pydantic_xml.BaseXmlModel, tag='hostname', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9\\.\\-]+')]

_hostname = hostname

class dns_host(pydantic_xml.BaseXmlModel, tag='host', search_mode='unordered'):
	ip: typing.Union[typing.Annotated[str, pydantic.Field(pattern='(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))')], typing.Annotated[str, pydantic.Field(pattern='(([0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){6}:[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){5}:([0-9A-Fa-f]{1,4}:)?[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){4}:([0-9A-Fa-f]{1,4}:){0,2}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){3}:([0-9A-Fa-f]{1,4}:){0,3}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){2}:([0-9A-Fa-f]{1,4}:){0,4}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){6}(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|(([0-9A-Fa-f]{1,4}:){0,5}:(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|(::([0-9A-Fa-f]{1,4}:){0,5}(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|([0-9A-Fa-f]{1,4}::([0-9A-Fa-f]{1,4}:){0,5}[0-9A-Fa-f]{1,4})|(::([0-9A-Fa-f]{1,4}:){0,6}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){1,7}:)|(::)')]] = pydantic_xml.attr(name='ip')
	hostname_list: typing.List[_hostname] = pydantic_xml.element(tag='hostname', min_length=1)

_dns_host = dns_host

class dns(pydantic_xml.BaseXmlModel, tag='dns', search_mode='unordered'):
	enable: typing.Optional[typing.Literal['yes', 'no']] = pydantic_xml.attr(name='enable', default=None)
	forward_plain_names: typing.Optional[typing.Literal['yes', 'no']] = pydantic_xml.attr(name='forwardPlainNames', default=None)
	forwarder_list: typing.Optional[typing.List[_forwarder]] = pydantic_xml.element(tag='forwarder', default=None)
	txt_list: typing.Optional[typing.List[_txt]] = pydantic_xml.element(tag='txt', default=None)
	srv_list: typing.Optional[typing.List[_srv]] = pydantic_xml.element(tag='srv', default=None)
	host_list: typing.Optional[typing.List[_dns_host]] = pydantic_xml.element(tag='host', default=None)

_dns = dns

class port_options(pydantic_xml.BaseXmlModel, tag='port', search_mode='strict'):
	isolated: typing.Optional[typing.Literal['yes', 'no']] = pydantic_xml.attr(name='isolated', default=None)

_port_options = port_options

class tftp(pydantic_xml.BaseXmlModel, tag='tftp', search_mode='strict'):
	root: str = pydantic_xml.attr(name='root')

_tftp = tftp

class lease(pydantic_xml.BaseXmlModel, tag='lease', search_mode='strict'):
	expiry: int = pydantic_xml.attr(name='expiry')
	unit: typing.Optional[typing.Literal['seconds', 'minutes', 'hours']] = pydantic_xml.attr(name='unit', default=None)

_lease = lease

class range(pydantic_xml.BaseXmlModel, tag='range', search_mode='unordered'):
	start: typing.Union[typing.Annotated[str, pydantic.Field(pattern='(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))')], typing.Annotated[str, pydantic.Field(pattern='(([0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){6}:[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){5}:([0-9A-Fa-f]{1,4}:)?[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){4}:([0-9A-Fa-f]{1,4}:){0,2}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){3}:([0-9A-Fa-f]{1,4}:){0,3}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){2}:([0-9A-Fa-f]{1,4}:){0,4}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){6}(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|(([0-9A-Fa-f]{1,4}:){0,5}:(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|(::([0-9A-Fa-f]{1,4}:){0,5}(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|([0-9A-Fa-f]{1,4}::([0-9A-Fa-f]{1,4}:){0,5}[0-9A-Fa-f]{1,4})|(::([0-9A-Fa-f]{1,4}:){0,6}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){1,7}:)|(::)')]] = pydantic_xml.attr(name='start')
	end: typing.Union[typing.Annotated[str, pydantic.Field(pattern='(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))')], typing.Annotated[str, pydantic.Field(pattern='(([0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){6}:[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){5}:([0-9A-Fa-f]{1,4}:)?[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){4}:([0-9A-Fa-f]{1,4}:){0,2}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){3}:([0-9A-Fa-f]{1,4}:){0,3}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){2}:([0-9A-Fa-f]{1,4}:){0,4}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){6}(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|(([0-9A-Fa-f]{1,4}:){0,5}:(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|(::([0-9A-Fa-f]{1,4}:){0,5}(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|([0-9A-Fa-f]{1,4}::([0-9A-Fa-f]{1,4}:){0,5}[0-9A-Fa-f]{1,4})|(::([0-9A-Fa-f]{1,4}:){0,6}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){1,7}:)|(::)')]] = pydantic_xml.attr(name='end')
	lease: typing.Optional[_lease] = pydantic_xml.element(tag='lease', default=None)

_range = range

class dhcp_host(pydantic_xml.BaseXmlModel, tag='host', search_mode='unordered'):
	mac: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9][02468aAcCeE](:[a-fA-F0-9]{2}){5}')]] = pydantic_xml.attr(name='mac', default=None)
	id: typing.Optional[typing.Union[typing.Annotated[str, pydantic.Field(pattern='[0]{1,2}:[0]{0,1}[1]:[0]{1,2}:[0]{0,1}[a-fA-F1-9](:[a-fA-F0-9]{1,2}){4}(:[a-fA-F0-9]{1,2}){6,8}')], typing.Annotated[str, pydantic.Field(pattern='[0]{1,2}:[0]{0,1}[2](:[a-fA-F0-9]{1,2}){4}(:[a-fA-F0-9]{1,2}){1,124}')], typing.Annotated[str, pydantic.Field(pattern='[0]{1,2}:[0]{0,1}[3]:[0]{1,2}:[0]{0,1}[a-fA-F1-9](:[a-fA-F0-9]{1,2}){6,8}')], typing.Annotated[str, pydantic.Field(pattern='[0]{1,2}:[0]{0,1}[4](:[a-fA-F0-9]{1,2}){16}')]]] = pydantic_xml.attr(name='id', default=None)
	name: typing.Optional[str] = pydantic_xml.attr(name='name', default=None)
	ip: typing.Union[typing.Annotated[str, pydantic.Field(pattern='(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))')], typing.Annotated[str, pydantic.Field(pattern='(([0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){6}:[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){5}:([0-9A-Fa-f]{1,4}:)?[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){4}:([0-9A-Fa-f]{1,4}:){0,2}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){3}:([0-9A-Fa-f]{1,4}:){0,3}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){2}:([0-9A-Fa-f]{1,4}:){0,4}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){6}(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|(([0-9A-Fa-f]{1,4}:){0,5}:(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|(::([0-9A-Fa-f]{1,4}:){0,5}(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|([0-9A-Fa-f]{1,4}::([0-9A-Fa-f]{1,4}:){0,5}[0-9A-Fa-f]{1,4})|(::([0-9A-Fa-f]{1,4}:){0,6}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){1,7}:)|(::)')]] = pydantic_xml.attr(name='ip')
	lease: typing.Optional[_lease] = pydantic_xml.element(tag='lease', default=None)

_dhcp_host = dhcp_host

class bootp(pydantic_xml.BaseXmlModel, tag='bootp', search_mode='strict'):
	file: typing.Annotated[str, pydantic.Field(pattern='.+')] = pydantic_xml.attr(name='file')
	server: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9\\.\\-]+')]] = pydantic_xml.attr(name='server', default=None)

_bootp = bootp

class dhcp(pydantic_xml.BaseXmlModel, tag='dhcp', search_mode='unordered'):
	range_list: typing.Optional[typing.List[_range]] = pydantic_xml.element(tag='range', default=None)
	host_list: typing.Optional[typing.List[_dhcp_host]] = pydantic_xml.element(tag='host', default=None)
	bootp: typing.Optional[_bootp] = pydantic_xml.element(tag='bootp', default=None)

_dhcp = dhcp

class ip(pydantic_xml.BaseXmlModel, tag='ip', search_mode='unordered'):
	address: typing.Optional[typing.Union[typing.Annotated[str, pydantic.Field(pattern='(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))')], typing.Annotated[str, pydantic.Field(pattern='(([0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){6}:[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){5}:([0-9A-Fa-f]{1,4}:)?[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){4}:([0-9A-Fa-f]{1,4}:){0,2}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){3}:([0-9A-Fa-f]{1,4}:){0,3}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){2}:([0-9A-Fa-f]{1,4}:){0,4}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){6}(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|(([0-9A-Fa-f]{1,4}:){0,5}:(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|(::([0-9A-Fa-f]{1,4}:){0,5}(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|([0-9A-Fa-f]{1,4}::([0-9A-Fa-f]{1,4}:){0,5}[0-9A-Fa-f]{1,4})|(::([0-9A-Fa-f]{1,4}:){0,6}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){1,7}:)|(::)')]]] = pydantic_xml.attr(name='address', default=None)
	netmask: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))')]] = pydantic_xml.attr(name='netmask', default=None)
	prefix: typing.Optional[int] = pydantic_xml.attr(name='prefix', default=None)
	family: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='(ipv4)|(ipv6)')]] = pydantic_xml.attr(name='family', default=None)
	local_ptr: typing.Optional[typing.Literal['yes', 'no']] = pydantic_xml.attr(name='localPtr', default=None)
	tftp: typing.Optional[_tftp] = pydantic_xml.element(tag='tftp', default=None)
	dhcp: typing.Optional[_dhcp] = pydantic_xml.element(tag='dhcp', default=None)

_ip = ip

class route(pydantic_xml.BaseXmlModel, tag='route', search_mode='unordered'):
	family: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='(ipv4)|(ipv6)')]] = pydantic_xml.attr(name='family', default=None)
	address: typing.Union[typing.Annotated[str, pydantic.Field(pattern='(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))')], typing.Annotated[str, pydantic.Field(pattern='(([0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){6}:[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){5}:([0-9A-Fa-f]{1,4}:)?[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){4}:([0-9A-Fa-f]{1,4}:){0,2}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){3}:([0-9A-Fa-f]{1,4}:){0,3}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){2}:([0-9A-Fa-f]{1,4}:){0,4}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){6}(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|(([0-9A-Fa-f]{1,4}:){0,5}:(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|(::([0-9A-Fa-f]{1,4}:){0,5}(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|([0-9A-Fa-f]{1,4}::([0-9A-Fa-f]{1,4}:){0,5}[0-9A-Fa-f]{1,4})|(::([0-9A-Fa-f]{1,4}:){0,6}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){1,7}:)|(::)')]] = pydantic_xml.attr(name='address')
	netmask: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))')]] = pydantic_xml.attr(name='netmask', default=None)
	prefix: typing.Optional[int] = pydantic_xml.attr(name='prefix', default=None)
	gateway: typing.Union[typing.Annotated[str, pydantic.Field(pattern='(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))')], typing.Annotated[str, pydantic.Field(pattern='(([0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){6}:[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){5}:([0-9A-Fa-f]{1,4}:)?[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){4}:([0-9A-Fa-f]{1,4}:){0,2}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){3}:([0-9A-Fa-f]{1,4}:){0,3}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){2}:([0-9A-Fa-f]{1,4}:){0,4}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){6}(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|(([0-9A-Fa-f]{1,4}:){0,5}:(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|(::([0-9A-Fa-f]{1,4}:){0,5}(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|([0-9A-Fa-f]{1,4}::([0-9A-Fa-f]{1,4}:){0,5}[0-9A-Fa-f]{1,4})|(::([0-9A-Fa-f]{1,4}:){0,6}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){1,7}:)|(::)')]] = pydantic_xml.attr(name='gateway')
	metric: typing.Optional[int] = pydantic_xml.attr(name='metric', default=None)

_route = route

class option(pydantic_xml.BaseXmlModel, tag='option', ns='dnsmasq', nsmap={'dnsmasq': 'http://libvirt.org/schemas/network/dnsmasq/1.0'}, search_mode='strict'):
	value: str = pydantic_xml.attr(name='value')

_option = option

class options(pydantic_xml.BaseXmlModel, tag='options', ns='dnsmasq', nsmap={'dnsmasq': 'http://libvirt.org/schemas/network/dnsmasq/1.0'}, search_mode='unordered'):
	option_list: typing.Optional[typing.List[_option]] = pydantic_xml.element(tag='option', default=None)

_options = options

class network(pydantic_xml.BaseXmlModel, tag='network', search_mode='unordered'):
	connections: typing.Optional[int] = pydantic_xml.attr(name='connections', default=None)
	ipv6: typing.Optional[typing.Literal['yes', 'no']] = pydantic_xml.attr(name='ipv6', default=None)
	trust_guest_rx_filters: typing.Optional[typing.Literal['yes', 'no']] = pydantic_xml.attr(name='trustGuestRxFilters', default=None)
	name: _name = pydantic_xml.element(tag='name')
	title: typing.Optional[_title] = pydantic_xml.element(tag='title', default=None)
	description: typing.Optional[_description] = pydantic_xml.element(tag='description', default=None)
	metadata: typing.Optional[_metadata] = pydantic_xml.element(tag='metadata', default=None)
	uuid: typing.Optional[_uuid] = pydantic_xml.element(tag='uuid', default=None)
	bridge: typing.Optional[_bridge] = pydantic_xml.element(tag='bridge', default=None)
	mtu: typing.Optional[_mtu] = pydantic_xml.element(tag='mtu', default=None)
	mac: typing.Optional[_mac] = pydantic_xml.element(tag='mac', default=None)
	forward: typing.Optional[_forward] = pydantic_xml.element(tag='forward', default=None)
	virtualport: typing.Optional[_virtualport] = pydantic_xml.element(tag='virtualport', default=None)
	portgroup_list: typing.Optional[typing.List[_portgroup]] = pydantic_xml.element(tag='portgroup', default=None)
	domain: typing.Optional[_domain] = pydantic_xml.element(tag='domain', default=None)
	dns: typing.Optional[_dns] = pydantic_xml.element(tag='dns', default=None)
	bandwidth: typing.Optional[_bandwidth] = pydantic_xml.element(tag='bandwidth', default=None)
	vlan: typing.Optional[_vlan] = pydantic_xml.element(tag='vlan', default=None)
	port: typing.Optional[_port_options] = pydantic_xml.element(tag='port', default=None)
	ip_list: typing.Optional[typing.List[_ip]] = pydantic_xml.element(tag='ip', default=None)
	route_list: typing.Optional[typing.List[_route]] = pydantic_xml.element(tag='route', default=None)
	dnsmasq_options: typing.Optional[_options] = pydantic_xml.element(tag='options', default=None)

_network = network

network = _network

