import typing
import pydantic
import pydantic_xml

# This file was automatically generated by relaxng-to-pydantic. Do not modify.
class uuid(pydantic_xml.BaseXmlModel, tag='uuid', search_mode='unordered'):
	value: typing.Union[typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{32}')], typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{8}\\-([a-fA-F0-9]{4}\\-){3}[a-fA-F0-9]{12}')]]

_uuid = uuid

class name(pydantic_xml.BaseXmlModel, tag='name', search_mode='strict'):
	value: str

_name = name

class owner(pydantic_xml.BaseXmlModel, tag='owner', search_mode='unordered'):
	name: _name = pydantic_xml.element(tag='name')
	uuid: _uuid = pydantic_xml.element(tag='uuid')

_owner = owner

class mac(pydantic_xml.BaseXmlModel, tag='mac', search_mode='strict'):
	address: typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9][02468aAcCeE](:[a-fA-F0-9]{2}){5}')] = pydantic_xml.attr(name='address')

_mac = mac

class group(pydantic_xml.BaseXmlModel, tag='group', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9_\\.\\-\\\\:/]+')]

_group = group

class rxfilters(pydantic_xml.BaseXmlModel, tag='rxfilters', search_mode='strict'):
	trust_guest: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='trustGuest')

_rxfilters = rxfilters

class virtualport_parameters(pydantic_xml.BaseXmlModel, tag='parameters', search_mode='unordered'):
	managerid: typing.Optional[typing.Annotated[int, pydantic.BeforeValidator(lambda v: (int(v) if v.isdigit() else int(v, 16)) if isinstance(v, str) else v)]] = pydantic_xml.attr(name='managerid', default=None)
	typeid: typing.Optional[typing.Annotated[int, pydantic.BeforeValidator(lambda v: (int(v) if v.isdigit() else int(v, 16)) if isinstance(v, str) else v)]] = pydantic_xml.attr(name='typeid', default=None)
	typeidversion: typing.Optional[typing.Annotated[int, pydantic.BeforeValidator(lambda v: (int(v) if v.isdigit() else int(v, 16)) if isinstance(v, str) else v)]] = pydantic_xml.attr(name='typeidversion', default=None)
	instanceid: typing.Optional[typing.Union[typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{32}')], typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{8}\\-([a-fA-F0-9]{4}\\-){3}[a-fA-F0-9]{12}')]]] = pydantic_xml.attr(name='instanceid', default=None)
	profileid: typing.Optional[str] = pydantic_xml.attr(name='profileid', default=None)
	interfaceid: typing.Optional[typing.Union[typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{32}')], typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{8}\\-([a-fA-F0-9]{4}\\-){3}[a-fA-F0-9]{12}')]]] = pydantic_xml.attr(name='interfaceid', default=None)

_virtualport_parameters = virtualport_parameters

class virtualport(pydantic_xml.BaseXmlModel, tag='virtualport', search_mode='unordered'):
	type: typing.Optional[typing.Literal['802.1Qbg', '802.1Qbh', 'openvswitch', 'midonet']] = pydantic_xml.attr(name='type', default=None)
	parameters: typing.Optional[_virtualport_parameters] = pydantic_xml.element(tag='parameters', default=None)

_virtualport = virtualport

class inbound(pydantic_xml.BaseXmlModel, tag='inbound', search_mode='strict'):
	average: typing.Optional[int] = pydantic_xml.attr(name='average', default=None)
	peak: typing.Optional[int] = pydantic_xml.attr(name='peak', default=None)
	floor: typing.Optional[int] = pydantic_xml.attr(name='floor', default=None)
	burst: typing.Optional[int] = pydantic_xml.attr(name='burst', default=None)

_inbound = inbound

class outbound(pydantic_xml.BaseXmlModel, tag='outbound', search_mode='strict'):
	average: typing.Optional[int] = pydantic_xml.attr(name='average', default=None)
	peak: typing.Optional[int] = pydantic_xml.attr(name='peak', default=None)
	floor: typing.Optional[int] = pydantic_xml.attr(name='floor', default=None)
	burst: typing.Optional[int] = pydantic_xml.attr(name='burst', default=None)

_outbound = outbound

class bandwidth(pydantic_xml.BaseXmlModel, tag='bandwidth', search_mode='unordered'):
	class_i_d: typing.Optional[int] = pydantic_xml.attr(name='classID', default=None)
	inbound: typing.Optional[_inbound] = pydantic_xml.element(tag='inbound', default=None)
	outbound: typing.Optional[_outbound] = pydantic_xml.element(tag='outbound', default=None)

_bandwidth = bandwidth

class tag(pydantic_xml.BaseXmlModel, tag='tag', search_mode='strict'):
	id: int = pydantic_xml.attr(name='id')
	native_mode: typing.Optional[typing.Literal['tagged', 'untagged']] = pydantic_xml.attr(name='nativeMode', default=None)

_tag = tag

class vlan(pydantic_xml.BaseXmlModel, tag='vlan', search_mode='unordered'):
	trunk: typing.Optional[typing.Literal['yes']] = pydantic_xml.attr(name='trunk', default=None)
	tag_list: typing.List[_tag] = pydantic_xml.element(tag='tag', min_length=1)

_vlan = vlan

class port_options(pydantic_xml.BaseXmlModel, tag='port', search_mode='strict'):
	isolated: typing.Optional[typing.Literal['yes', 'no']] = pydantic_xml.attr(name='isolated', default=None)

_port_options = port_options

class hostdev_driver(pydantic_xml.BaseXmlModel, tag='driver', search_mode='strict'):
	name: typing.Optional[typing.Literal['kvm', 'vfio', 'xen']] = pydantic_xml.attr(name='name', default=None)
	model: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9_\\+\\-]+')]] = pydantic_xml.attr(name='model', default=None)

_hostdev_driver = hostdev_driver

class address(pydantic_xml.BaseXmlModel, tag='address', search_mode='strict'):
	domain: typing.Optional[typing.Annotated[int, pydantic.BeforeValidator(lambda v: (int(v) if v.isdigit() else int(v, 16)) if isinstance(v, str) else v)]] = pydantic_xml.attr(name='domain', default=None)
	bus: typing.Optional[typing.Annotated[int, pydantic.BeforeValidator(lambda v: (int(v) if v.isdigit() else int(v, 16)) if isinstance(v, str) else v)]] = pydantic_xml.attr(name='bus', default=None)
	slot: typing.Optional[typing.Annotated[int, pydantic.BeforeValidator(lambda v: (int(v) if v.isdigit() else int(v, 16)) if isinstance(v, str) else v)]] = pydantic_xml.attr(name='slot', default=None)
	function: typing.Optional[typing.Annotated[int, pydantic.BeforeValidator(lambda v: (int(v) if v.isdigit() else int(v, 16)) if isinstance(v, str) else v)]] = pydantic_xml.attr(name='function', default=None)
	multifunction: typing.Optional[typing.Literal['on', 'off']] = pydantic_xml.attr(name='multifunction', default=None)

_address = address

class plug(pydantic_xml.BaseXmlModel, tag='plug', search_mode='unordered'):
	type: typing.Literal['network', 'bridge', 'direct', 'hostdev-pci'] = pydantic_xml.attr(name='type')
	bridge: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9_\\.\\-\\\\:/]+')]] = pydantic_xml.attr(name='bridge', default=None)
	mac_table_manager: typing.Optional[typing.Literal['kernel', 'libvirt']] = pydantic_xml.attr(name='macTableManager', default=None)
	dev: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9_\\.\\-\\\\:/]+')]] = pydantic_xml.attr(name='dev', default=None)
	mode: typing.Optional[typing.Literal['bridge', 'passthrough', 'private', 'vepa']] = pydantic_xml.attr(name='mode', default=None)
	managed: typing.Optional[typing.Literal['yes', 'no']] = pydantic_xml.attr(name='managed', default=None)
	driver: typing.Optional[_hostdev_driver] = pydantic_xml.element(tag='driver', default=None)
	address: typing.Optional[_address] = pydantic_xml.element(tag='address', default=None)

_plug = plug

class networkport(pydantic_xml.BaseXmlModel, tag='networkport', search_mode='unordered'):
	uuid: _uuid = pydantic_xml.element(tag='uuid')
	owner: _owner = pydantic_xml.element(tag='owner')
	mac: _mac = pydantic_xml.element(tag='mac')
	group: typing.Optional[_group] = pydantic_xml.element(tag='group', default=None)
	rxfilters: typing.Optional[_rxfilters] = pydantic_xml.element(tag='rxfilters', default=None)
	virtualport: typing.Optional[_virtualport] = pydantic_xml.element(tag='virtualport', default=None)
	bandwidth: typing.Optional[_bandwidth] = pydantic_xml.element(tag='bandwidth', default=None)
	vlan: typing.Optional[_vlan] = pydantic_xml.element(tag='vlan', default=None)
	port: typing.Optional[_port_options] = pydantic_xml.element(tag='port', default=None)
	plug: typing.Optional[_plug] = pydantic_xml.element(tag='plug', default=None)

_networkport = networkport

networkport = _networkport

