import typing
import pydantic
import pydantic_xml

# This file was automatically generated by relaxng-to-pydantic. Do not modify.
class device_name(pydantic_xml.BaseXmlModel, tag='name', search_mode='strict'):
	value: str

_device_name = device_name

class path(pydantic_xml.BaseXmlModel, tag='path', search_mode='strict'):
	value: str

_path = path

class devnode(pydantic_xml.BaseXmlModel, tag='devnode', search_mode='strict'):
	value: str
	type: typing.Literal['dev', 'link'] = pydantic_xml.attr(name='type')

_devnode = devnode

class parent(pydantic_xml.BaseXmlModel, tag='parent', search_mode='unordered'):
	value: typing.Optional[str] = None
	wwnn: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='(0x)?[0-9a-fA-F]{16}')]] = pydantic_xml.attr(name='wwnn', default=None)
	wwpn: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='(0x)?[0-9a-fA-F]{16}')]] = pydantic_xml.attr(name='wwpn', default=None)
	fabric_wwn: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='(0x)?[0-9a-fA-F]{16}')]] = pydantic_xml.attr(name='fabric_wwn', default=None)

_parent = parent

class driver(pydantic_xml.BaseXmlModel, tag='driver', search_mode='strict'):
	name: _device_name = pydantic_xml.element(tag='name')

_driver = driver

class hardware_vendor(pydantic_xml.BaseXmlModel, tag='vendor', search_mode='strict'):
	value: str

_hardware_vendor = hardware_vendor

class version(pydantic_xml.BaseXmlModel, tag='version', search_mode='strict'):
	value: str

_version = version

class serial(pydantic_xml.BaseXmlModel, tag='serial', search_mode='strict'):
	value: str

_serial = serial

class uuid(pydantic_xml.BaseXmlModel, tag='uuid', search_mode='unordered'):
	value: typing.Union[typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{32}')], typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{8}\\-([a-fA-F0-9]{4}\\-){3}[a-fA-F0-9]{12}')]]

_uuid = uuid

class hardware(pydantic_xml.BaseXmlModel, tag='hardware', search_mode='strict'):
	vendor: typing.Optional[_hardware_vendor] = pydantic_xml.element(tag='vendor', default=None)
	version: typing.Optional[_version] = pydantic_xml.element(tag='version', default=None)
	serial: typing.Optional[_serial] = pydantic_xml.element(tag='serial', default=None)
	uuid: _uuid = pydantic_xml.element(tag='uuid')

_hardware = hardware

class release_date(pydantic_xml.BaseXmlModel, tag='release_date', search_mode='strict'):
	value: str

_release_date = release_date

class firmware(pydantic_xml.BaseXmlModel, tag='firmware', search_mode='strict'):
	vendor: typing.Optional[_hardware_vendor] = pydantic_xml.element(tag='vendor', default=None)
	version: typing.Optional[_version] = pydantic_xml.element(tag='version', default=None)
	release_date: typing.Optional[_release_date] = pydantic_xml.element(tag='release_date', default=None)

_firmware = firmware

class domain(pydantic_xml.BaseXmlModel, tag='domain', search_mode='strict'):
	value: int

_domain = domain

class slot(pydantic_xml.BaseXmlModel, tag='slot', search_mode='strict'):
	value: int

_slot = slot

class function(pydantic_xml.BaseXmlModel, tag='function', search_mode='strict'):
	value: int

_function = function

class Variant_address(pydantic_xml.BaseXmlModel, tag='address', search_mode='strict'):
	model_config = {'extra': 'forbid'}
	domain: typing.Annotated[str, pydantic.Field(pattern='(0x)?[0-9a-f]+')] = pydantic_xml.attr(name='domain')
	bus: typing.Annotated[str, pydantic.Field(pattern='(0x)?[0-9a-f]+')] = pydantic_xml.attr(name='bus')
	slot: typing.Annotated[str, pydantic.Field(pattern='(0x)?[0-9a-f]+')] = pydantic_xml.attr(name='slot')
	function: typing.Annotated[str, pydantic.Field(pattern='(0x)?[0-9a-f]+')] = pydantic_xml.attr(name='function')

_Variant_address = Variant_address

class device_a_p_i(pydantic_xml.BaseXmlModel, tag='deviceAPI', search_mode='unordered'):
	value: typing.Literal['vfio-pci', 'vfio-ccw', 'vfio-ap']

_device_a_p_i = device_a_p_i

class available_instances(pydantic_xml.BaseXmlModel, tag='availableInstances', search_mode='strict'):
	value: int

_available_instances = available_instances

class Variant_type(pydantic_xml.BaseXmlModel, tag='type', search_mode='strict'):
	id: str = pydantic_xml.attr(name='id')
	name: typing.Optional[_device_name] = pydantic_xml.element(tag='name', default=None)
	device_a_p_i: _device_a_p_i = pydantic_xml.element(tag='deviceAPI')
	available_instances: _available_instances = pydantic_xml.element(tag='availableInstances')

_Variant_type = Variant_type

class Variant_name(pydantic_xml.BaseXmlModel, tag='name', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='.{0,255}')]

_Variant_name = Variant_name

class change_level(pydantic_xml.BaseXmlModel, tag='change_level', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='.{0,255}')]

_change_level = change_level

class manufacture_id(pydantic_xml.BaseXmlModel, tag='manufacture_id', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='.{0,255}')]

_manufacture_id = manufacture_id

class part_number(pydantic_xml.BaseXmlModel, tag='part_number', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='.{0,255}')]

_part_number = part_number

class serial_number(pydantic_xml.BaseXmlModel, tag='serial_number', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='.{0,255}')]

_serial_number = serial_number

class vendor_field(pydantic_xml.BaseXmlModel, tag='vendor_field', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='.{0,255}')]
	index: typing.Annotated[str, pydantic.Field(pattern='[0-9A-Z]{1}')] = pydantic_xml.attr(name='index')

_vendor_field = vendor_field

class asset_tag(pydantic_xml.BaseXmlModel, tag='asset_tag', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='.{0,255}')]

_asset_tag = asset_tag

class system_field(pydantic_xml.BaseXmlModel, tag='system_field', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='.{0,255}')]
	index: typing.Annotated[str, pydantic.Field(pattern='[0-9B-Z]{1}')] = pydantic_xml.attr(name='index')

_system_field = system_field

class fields(pydantic_xml.BaseXmlModel, tag='fields', search_mode='unordered'):
	access: typing.Literal['readonly', 'readwrite'] = pydantic_xml.attr(name='access')
	change_level: typing.Optional[_change_level] = pydantic_xml.element(tag='change_level', default=None)
	manufacture_id: typing.Optional[_manufacture_id] = pydantic_xml.element(tag='manufacture_id', default=None)
	part_number: typing.Optional[_part_number] = pydantic_xml.element(tag='part_number', default=None)
	serial_number: typing.Optional[_serial_number] = pydantic_xml.element(tag='serial_number', default=None)
	vendor_field_list: typing.Optional[typing.List[_vendor_field]] = pydantic_xml.element(tag='vendor_field', default=None)
	asset_tag: typing.Optional[_asset_tag] = pydantic_xml.element(tag='asset_tag', default=None)
	system_field_list: typing.Optional[typing.List[_system_field]] = pydantic_xml.element(tag='system_field', default=None)

_fields = fields

class cappcidev_capability(pydantic_xml.BaseXmlModel, tag='capability', search_mode='unordered'):
	model_config = {'extra': 'forbid'}
	type: typing.Literal['phys_function', 'virt_functions', 'pci-bridge', 'cardbus-bridge', 'mdev_types', 'vpd'] = pydantic_xml.attr(name='type')
	address: typing.Optional[typing.List[typing.Union[_Variant_address, _Variant_address]]] = pydantic_xml.element(tag='address', default=None)
	max_count: typing.Optional[int] = pydantic_xml.attr(name='maxCount', default=None)
	type_list: typing.Optional[typing.List[_Variant_type]] = pydantic_xml.element(tag='type', default=None)
	name: typing.Optional[_Variant_name] = pydantic_xml.element(tag='name', default=None)
	fields: typing.Optional[_fields] = pydantic_xml.element(tag='fields', default=None)

_cappcidev_capability = cappcidev_capability

class numa(pydantic_xml.BaseXmlModel, tag='numa', search_mode='strict'):
	node: typing.Optional[int] = pydantic_xml.attr(name='node', default=None)

_numa = numa

class pci_express_link(pydantic_xml.BaseXmlModel, tag='link', search_mode='strict'):
	validity: typing.Literal['cap', 'sta'] = pydantic_xml.attr(name='validity')
	port: typing.Optional[int] = pydantic_xml.attr(name='port', default=None)
	speed: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='[0-9]+(.[0-9]+)?')]] = pydantic_xml.attr(name='speed', default=None)
	width: int = pydantic_xml.attr(name='width')

_pci_express_link = pci_express_link

class pci_express(pydantic_xml.BaseXmlModel, tag='pci-express', search_mode='unordered'):
	link_list: typing.Optional[typing.List[_pci_express_link]] = pydantic_xml.element(tag='link', default=None)

_pci_express = pci_express

class capusbdev_device(pydantic_xml.BaseXmlModel, tag='device', search_mode='strict'):
	value: int

_capusbdev_device = capusbdev_device

class number(pydantic_xml.BaseXmlModel, tag='number', search_mode='strict'):
	value: int

_number = number

class subclass(pydantic_xml.BaseXmlModel, tag='subclass', search_mode='strict'):
	value: int

_subclass = subclass

class protocol(pydantic_xml.BaseXmlModel, tag='protocol', search_mode='strict'):
	value: int

_protocol = protocol

class description(pydantic_xml.BaseXmlModel, tag='description', search_mode='strict'):
	value: str

_description = description

class interface(pydantic_xml.BaseXmlModel, tag='interface', search_mode='strict'):
	value: str

_interface = interface

class capnet_address(pydantic_xml.BaseXmlModel, tag='address', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='([a-fA-F0-9]{2}:){5}[a-fA-F0-9]{2}')]

_capnet_address = capnet_address

class link_speed_state_link(pydantic_xml.BaseXmlModel, tag='link', search_mode='strict'):
	speed: typing.Optional[int] = pydantic_xml.attr(name='speed', default=None)
	state: typing.Optional[typing.Literal['unknown', 'notpresent', 'down', 'lowerlayerdown', 'testing', 'dormant', 'up']] = pydantic_xml.attr(name='state', default=None)

_link_speed_state_link = link_speed_state_link

class feature(pydantic_xml.BaseXmlModel, tag='feature', search_mode='strict'):
	name: typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z\\-_]+')] = pydantic_xml.attr(name='name')

_feature = feature

class subcapnet(pydantic_xml.BaseXmlModel, tag='capability', search_mode='unordered'):
	model_config = {'extra': 'forbid'}
	type: typing.Literal['80203', '80211'] = pydantic_xml.attr(name='type')

_subcapnet = subcapnet

class char(pydantic_xml.BaseXmlModel, tag='char', search_mode='strict'):
	value: str

_char = char

class host(pydantic_xml.BaseXmlModel, tag='host', search_mode='strict'):
	value: int

_host = host

class unique_id(pydantic_xml.BaseXmlModel, tag='unique_id', search_mode='strict'):
	value: int

_unique_id = unique_id

class wwnn(pydantic_xml.BaseXmlModel, tag='wwnn', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='(0x)?[0-9a-fA-F]{16}')]

_wwnn = wwnn

class wwpn(pydantic_xml.BaseXmlModel, tag='wwpn', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='(0x)?[0-9a-fA-F]{16}')]

_wwpn = wwpn

class fabric_wwn(pydantic_xml.BaseXmlModel, tag='fabric_wwn', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='(0x)?[0-9a-fA-F]{16}')]

_fabric_wwn = fabric_wwn

class max_vports(pydantic_xml.BaseXmlModel, tag='max_vports', search_mode='strict'):
	value: int

_max_vports = max_vports

class vports(pydantic_xml.BaseXmlModel, tag='vports', search_mode='strict'):
	value: int

_vports = vports

class capscsihost_capability(pydantic_xml.BaseXmlModel, tag='capability', search_mode='unordered'):
	model_config = {'extra': 'forbid'}
	type: typing.Literal['fc_host', 'vport_ops'] = pydantic_xml.attr(name='type')
	wwnn: typing.Optional[_wwnn] = pydantic_xml.element(tag='wwnn', default=None)
	wwpn: typing.Optional[_wwpn] = pydantic_xml.element(tag='wwpn', default=None)
	fabric_wwn: typing.Optional[_fabric_wwn] = pydantic_xml.element(tag='fabric_wwn', default=None)
	max_vports: typing.Optional[_max_vports] = pydantic_xml.element(tag='max_vports', default=None)
	vports: typing.Optional[_vports] = pydantic_xml.element(tag='vports', default=None)

_capscsihost_capability = capscsihost_capability

class rport(pydantic_xml.BaseXmlModel, tag='rport', search_mode='strict'):
	value: str

_rport = rport

class capscsitarget_capability(pydantic_xml.BaseXmlModel, tag='capability', search_mode='strict'):
	model_config = {'extra': 'forbid'}
	type: typing.Literal['fc_remote_port'] = pydantic_xml.attr(name='type')
	rport: _rport = pydantic_xml.element(tag='rport')
	wwpn: _wwpn = pydantic_xml.element(tag='wwpn')

_capscsitarget_capability = capscsitarget_capability

class lun(pydantic_xml.BaseXmlModel, tag='lun', search_mode='strict'):
	value: int

_lun = lun

class block(pydantic_xml.BaseXmlModel, tag='block', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='/[a-zA-Z0-9_\\+\\-/%]+')]

_block = block

class drive_type(pydantic_xml.BaseXmlModel, tag='drive_type', search_mode='strict'):
	value: str

_drive_type = drive_type

class model(pydantic_xml.BaseXmlModel, tag='model', search_mode='strict'):
	value: str

_model = model

class media_available(pydantic_xml.BaseXmlModel, tag='media_available', search_mode='unordered'):
	value: typing.Literal['1', '0']

_media_available = media_available

class media_size(pydantic_xml.BaseXmlModel, tag='media_size', search_mode='strict'):
	value: int

_media_size = media_size

class media_label(pydantic_xml.BaseXmlModel, tag='media_label', search_mode='strict'):
	value: str

_media_label = media_label

class logical_block_size(pydantic_xml.BaseXmlModel, tag='logical_block_size', search_mode='strict'):
	value: int

_logical_block_size = logical_block_size

class num_blocks(pydantic_xml.BaseXmlModel, tag='num_blocks', search_mode='strict'):
	value: int

_num_blocks = num_blocks

class capstorageremoveable(pydantic_xml.BaseXmlModel, tag='capability', search_mode='strict'):
	model_config = {'extra': 'forbid'}
	type: typing.Literal['removable'] = pydantic_xml.attr(name='type')
	media_available: _media_available = pydantic_xml.element(tag='media_available')
	media_size: _media_size = pydantic_xml.element(tag='media_size')
	media_label: typing.Optional[_media_label] = pydantic_xml.element(tag='media_label', default=None)
	logical_block_size: typing.Optional[_logical_block_size] = pydantic_xml.element(tag='logical_block_size', default=None)
	num_blocks: typing.Optional[_num_blocks] = pydantic_xml.element(tag='num_blocks', default=None)

_capstorageremoveable = capstorageremoveable

class size(pydantic_xml.BaseXmlModel, tag='size', search_mode='strict'):
	value: int

_size = size

class capstorage_capability(pydantic_xml.BaseXmlModel, tag='capability', search_mode='strict'):
	model_config = {'extra': 'forbid'}
	type: typing.Literal['hotpluggable'] = pydantic_xml.attr(name='type')

_capstorage_capability = capstorage_capability

class parent_addr(pydantic_xml.BaseXmlModel, tag='parent_addr', search_mode='strict'):
	value: str

_parent_addr = parent_addr

class attr(pydantic_xml.BaseXmlModel, tag='attr', search_mode='strict'):
	name: str = pydantic_xml.attr(name='name')
	value: str = pydantic_xml.attr(name='value')

_attr = attr

class state(pydantic_xml.BaseXmlModel, tag='state', search_mode='unordered'):
	value: typing.Literal['online', 'offline']

_state = state

class cssid(pydantic_xml.BaseXmlModel, tag='cssid', search_mode='unordered'):
	value: typing.Union[typing.Annotated[str, pydantic.Field(pattern='0x[0-9a-eA-E][0-9a-fA-F]?')], typing.Annotated[str, pydantic.Field(pattern='0x[fF][0-9a-eA-E]?')], int]

_cssid = cssid

class ssid(pydantic_xml.BaseXmlModel, tag='ssid', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='(0x)?[0-3]')]

_ssid = ssid

class devno(pydantic_xml.BaseXmlModel, tag='devno', search_mode='unordered'):
	value: typing.Union[typing.Annotated[str, pydantic.Field(pattern='0x[0-9a-fA-F]{1,4}')], int]

_devno = devno

class group_device(pydantic_xml.BaseXmlModel, tag='group_device', search_mode='strict'):
	value: str

_group_device = group_device

class capccwgroupmember_capability(pydantic_xml.BaseXmlModel, tag='capability', search_mode='strict'):
	model_config = {'extra': 'forbid'}
	type: typing.Literal['ccwgroup_member'] = pydantic_xml.attr(name='type')
	group_device: _group_device = pydantic_xml.element(tag='group_device')

_capccwgroupmember_capability = capccwgroupmember_capability

class ccw_device(pydantic_xml.BaseXmlModel, tag='ccw_device', search_mode='strict'):
	value: str
	ref: str = pydantic_xml.attr(name='ref')

_ccw_device = ccw_device

class members(pydantic_xml.BaseXmlModel, tag='members', search_mode='unordered'):
	ccw_device_list: typing.List[_ccw_device] = pydantic_xml.element(tag='ccw_device', min_length=1)

_members = members

class card_type(pydantic_xml.BaseXmlModel, tag='card_type', search_mode='strict'):
	value: str

_card_type = card_type

class chpid(pydantic_xml.BaseXmlModel, tag='chpid', search_mode='strict'):
	value: str

_chpid = chpid

class capccwgroupdev_capability(pydantic_xml.BaseXmlModel, tag='capability', search_mode='unordered'):
	model_config = {'extra': 'forbid'}
	type: typing.Literal['qeth_generic', 'qeth_layer2', 'qeth_layer3'] = pydantic_xml.attr(name='type')
	card_type: _card_type = pydantic_xml.element(tag='card_type')
	chpid: _chpid = pydantic_xml.element(tag='chpid')

_capccwgroupdev_capability = capccwgroupdev_capability

class channel_dev_addr(pydantic_xml.BaseXmlModel, tag='channel_dev_addr', search_mode='unordered'):
	cssid: _cssid = pydantic_xml.element(tag='cssid')
	ssid: _ssid = pydantic_xml.element(tag='ssid')
	devno: _devno = pydantic_xml.element(tag='devno')

_channel_dev_addr = channel_dev_addr

class mdev_types(pydantic_xml.BaseXmlModel, tag='capability', search_mode='unordered'):
	model_config = {'extra': 'forbid'}
	type: typing.Literal['mdev_types'] = pydantic_xml.attr(name='type')
	type_list: typing.List[_Variant_type] = pydantic_xml.element(tag='type', min_length=1)

_mdev_types = mdev_types

class chardev(pydantic_xml.BaseXmlModel, tag='chardev', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='/[a-zA-Z0-9_\\+\\-/%]+')]

_chardev = chardev

class ap_adapter(pydantic_xml.BaseXmlModel, tag='ap-adapter', search_mode='unordered'):
	value: typing.Union[typing.Annotated[str, pydantic.Field(pattern='0x[0-9a-fA-F]{1,2}')], int]

_ap_adapter = ap_adapter

class ap_domain(pydantic_xml.BaseXmlModel, tag='ap-domain', search_mode='unordered'):
	value: typing.Union[typing.Annotated[str, pydantic.Field(pattern='0x[0-9a-fA-F]{1,4}')], int]

_ap_domain = ap_domain

class capability_product(pydantic_xml.BaseXmlModel, tag='product', search_mode='unordered'):
	value: str
	id: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='(0x)?[0-9a-f]+')]] = pydantic_xml.attr(name='id', default=None)

_capability_product = capability_product

class capability_class_(pydantic_xml.BaseXmlModel, tag='class', search_mode='unordered'):
	value: typing.Union[typing.Annotated[str, pydantic.Field(pattern='0x[0-9a-fA-F]{6}')], int]

_capability_class_ = capability_class_

class capability_bus(pydantic_xml.BaseXmlModel, tag='bus', search_mode='unordered'):
	value: typing.Union[int, str]

_capability_bus = capability_bus

class capability_vendor(pydantic_xml.BaseXmlModel, tag='vendor', search_mode='unordered'):
	value: str
	id: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='(0x)?[0-9a-f]+')]] = pydantic_xml.attr(name='id', default=None)

_capability_vendor = capability_vendor

class capability_iommu_group(pydantic_xml.BaseXmlModel, tag='iommuGroup', search_mode='unordered'):
	number: int = pydantic_xml.attr(name='number')
	address_list: typing.Optional[typing.List[_Variant_address]] = pydantic_xml.element(tag='address', default=None)

_capability_iommu_group = capability_iommu_group

class capability_target(pydantic_xml.BaseXmlModel, tag='target', search_mode='unordered'):
	value: typing.Union[str, int]

_capability_target = capability_target

class capability_type(pydantic_xml.BaseXmlModel, tag='type', search_mode='unordered'):
	value: typing.Optional[typing.Union[str, typing.Literal['primary', 'control', 'render']]] = None
	id: typing.Optional[str] = pydantic_xml.attr(name='id', default=None)

_capability_type = capability_type

class device_capability(pydantic_xml.BaseXmlModel, tag='capability', search_mode='unordered'):
	type: typing.Literal['system', 'pci', 'usb_device', 'usb', 'net', 'scsi_generic', 'scsi_host', 'scsi_target', 'scsi', 'storage', 'drm', 'mdev', 'ccw', 'ccwgroup', 'css', 'vdpa', 'ap_card', 'ap_queue', 'ap_matrix'] = pydantic_xml.attr(name='type')
	product: typing.Optional[_capability_product] = pydantic_xml.element(tag='product', default=None)
	hardware: typing.Optional[_hardware] = pydantic_xml.element(tag='hardware', default=None)
	firmware: typing.Optional[_firmware] = pydantic_xml.element(tag='firmware', default=None)
	class_: typing.Optional[_capability_class_] = pydantic_xml.element(tag='class', default=None)
	domain: typing.Optional[_domain] = pydantic_xml.element(tag='domain', default=None)
	bus: typing.Optional[_capability_bus] = pydantic_xml.element(tag='bus', default=None)
	slot: typing.Optional[_slot] = pydantic_xml.element(tag='slot', default=None)
	function: typing.Optional[_function] = pydantic_xml.element(tag='function', default=None)
	vendor: typing.Optional[_capability_vendor] = pydantic_xml.element(tag='vendor', default=None)
	capability: typing.Optional[typing.List[typing.Union[_cappcidev_capability, _subcapnet, _capscsihost_capability, _capscsitarget_capability, _capstorageremoveable, _capstorage_capability, _capccwgroupmember_capability, _capccwgroupdev_capability, _mdev_types]]] = pydantic_xml.element(tag='capability', default=None)
	iommu_group: typing.Optional[_capability_iommu_group] = pydantic_xml.element(tag='iommuGroup', default=None)
	numa: typing.Optional[_numa] = pydantic_xml.element(tag='numa', default=None)
	pci_express: typing.Optional[_pci_express] = pydantic_xml.element(tag='pci-express', default=None)
	device: typing.Optional[_capusbdev_device] = pydantic_xml.element(tag='device', default=None)
	number: typing.Optional[_number] = pydantic_xml.element(tag='number', default=None)
	subclass: typing.Optional[_subclass] = pydantic_xml.element(tag='subclass', default=None)
	protocol: typing.Optional[_protocol] = pydantic_xml.element(tag='protocol', default=None)
	description: typing.Optional[_description] = pydantic_xml.element(tag='description', default=None)
	interface: typing.Optional[_interface] = pydantic_xml.element(tag='interface', default=None)
	address: typing.Optional[_capnet_address] = pydantic_xml.element(tag='address', default=None)
	link: typing.Optional[_link_speed_state_link] = pydantic_xml.element(tag='link', default=None)
	feature_list: typing.Optional[typing.List[_feature]] = pydantic_xml.element(tag='feature', default=None)
	char: typing.Optional[_char] = pydantic_xml.element(tag='char', default=None)
	host: typing.Optional[_host] = pydantic_xml.element(tag='host', default=None)
	unique_id: typing.Optional[_unique_id] = pydantic_xml.element(tag='unique_id', default=None)
	target: typing.Optional[_capability_target] = pydantic_xml.element(tag='target', default=None)
	lun: typing.Optional[_lun] = pydantic_xml.element(tag='lun', default=None)
	type2: typing.Optional[_capability_type] = pydantic_xml.element(tag='type', default=None)
	block: typing.Optional[_block] = pydantic_xml.element(tag='block', default=None)
	drive_type: typing.Optional[_drive_type] = pydantic_xml.element(tag='drive_type', default=None)
	model: typing.Optional[_model] = pydantic_xml.element(tag='model', default=None)
	serial: typing.Optional[_serial] = pydantic_xml.element(tag='serial', default=None)
	size: typing.Optional[_size] = pydantic_xml.element(tag='size', default=None)
	logical_block_size: typing.Optional[_logical_block_size] = pydantic_xml.element(tag='logical_block_size', default=None)
	num_blocks: typing.Optional[_num_blocks] = pydantic_xml.element(tag='num_blocks', default=None)
	uuid: typing.Optional[_uuid] = pydantic_xml.element(tag='uuid', default=None)
	parent_addr: typing.Optional[_parent_addr] = pydantic_xml.element(tag='parent_addr', default=None)
	attr_list: typing.Optional[typing.List[_attr]] = pydantic_xml.element(tag='attr', default=None)
	state: typing.Optional[_state] = pydantic_xml.element(tag='state', default=None)
	cssid: typing.Optional[_cssid] = pydantic_xml.element(tag='cssid', default=None)
	ssid: typing.Optional[_ssid] = pydantic_xml.element(tag='ssid', default=None)
	devno: typing.Optional[_devno] = pydantic_xml.element(tag='devno', default=None)
	members: typing.Optional[_members] = pydantic_xml.element(tag='members', default=None)
	channel_dev_addr: typing.Optional[_channel_dev_addr] = pydantic_xml.element(tag='channel_dev_addr', default=None)
	chardev: typing.Optional[_chardev] = pydantic_xml.element(tag='chardev', default=None)
	ap_adapter: typing.Optional[_ap_adapter] = pydantic_xml.element(tag='ap-adapter', default=None)
	ap_domain: typing.Optional[_ap_domain] = pydantic_xml.element(tag='ap-domain', default=None)

_device_capability = device_capability

class device_device(pydantic_xml.BaseXmlModel, tag='device', search_mode='unordered'):
	name: _device_name = pydantic_xml.element(tag='name')
	path: typing.Optional[_path] = pydantic_xml.element(tag='path', default=None)
	devnode_list: typing.Optional[typing.List[_devnode]] = pydantic_xml.element(tag='devnode', default=None)
	parent: typing.Optional[_parent] = pydantic_xml.element(tag='parent', default=None)
	driver: typing.Optional[_driver] = pydantic_xml.element(tag='driver', default=None)
	capability_list: typing.Optional[typing.List[_device_capability]] = pydantic_xml.element(tag='capability', default=None)

_device_device = device_device

nodedev = _device_device

