import typing
import pydantic
import pydantic_xml

# This file was automatically generated by relaxng-to-pydantic. Do not modify.
class name(pydantic_xml.BaseXmlModel, tag='name', search_mode='strict'):
	value: str

_name = name

class uuid(pydantic_xml.BaseXmlModel, tag='uuid', search_mode='unordered'):
	value: typing.Union[typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{32}')], typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{8}\\-([a-fA-F0-9]{4}\\-){3}[a-fA-F0-9]{12}')]]

_uuid = uuid

class owner(pydantic_xml.BaseXmlModel, tag='owner', search_mode='unordered'):
	name: _name = pydantic_xml.element(tag='name')
	uuid: _uuid = pydantic_xml.element(tag='uuid')

_owner = owner

class portdev(pydantic_xml.BaseXmlModel, tag='portdev', search_mode='strict'):
	name: str = pydantic_xml.attr(name='name')

_portdev = portdev

class linkdev(pydantic_xml.BaseXmlModel, tag='linkdev', search_mode='strict'):
	name: str = pydantic_xml.attr(name='name')

_linkdev = linkdev

class mac(pydantic_xml.BaseXmlModel, tag='mac', search_mode='strict'):
	address: typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9][02468aAcCeE](:[a-fA-F0-9]{2}){5}')] = pydantic_xml.attr(name='address')

_mac = mac

class parameter(pydantic_xml.BaseXmlModel, tag='parameter', search_mode='strict'):
	name: typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9_]+')] = pydantic_xml.attr(name='name')
	value: typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9_\\.:]+')] = pydantic_xml.attr(name='value')

_parameter = parameter

class filterref(pydantic_xml.BaseXmlModel, tag='filterref', search_mode='unordered'):
	filter: str = pydantic_xml.attr(name='filter')
	parameter_list: typing.Optional[typing.List[_parameter]] = pydantic_xml.element(tag='parameter', default=None)

_filterref = filterref

class filterbinding(pydantic_xml.BaseXmlModel, tag='filterbinding', search_mode='unordered'):
	owner: _owner = pydantic_xml.element(tag='owner')
	portdev: _portdev = pydantic_xml.element(tag='portdev')
	linkdev: typing.Optional[_linkdev] = pydantic_xml.element(tag='linkdev', default=None)
	mac: _mac = pydantic_xml.element(tag='mac')
	filterref: _filterref = pydantic_xml.element(tag='filterref')

_filterbinding = filterbinding

nwfilterbinding = _filterbinding

