import typing
import pydantic
import pydantic_xml

# This file was automatically generated by relaxng-to-pydantic. Do not modify.
class uuid(pydantic_xml.BaseXmlModel, tag='uuid', search_mode='unordered'):
	value: typing.Union[typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{32}')], typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{8}\\-([a-fA-F0-9]{4}\\-){3}[a-fA-F0-9]{12}')]]

_uuid = uuid

class description(pydantic_xml.BaseXmlModel, tag='description', search_mode='strict'):
	value: str

_description = description

class volume(pydantic_xml.BaseXmlModel, tag='volume', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='(/|[a-zA-Z]:\\\\).+')]

_volume = volume

class name(pydantic_xml.BaseXmlModel, tag='name', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='[^/\\n]+')]

_name = name

class target(pydantic_xml.BaseXmlModel, tag='target', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='[^/\\n]+')]

_target = target

class usage(pydantic_xml.BaseXmlModel, tag='usage', search_mode='unordered'):
	type: typing.Literal['volume', 'ceph', 'iscsi', 'tls', 'vtpm'] = pydantic_xml.attr(name='type')
	volume: typing.Optional[_volume] = pydantic_xml.element(tag='volume', default=None)
	name: typing.Optional[_name] = pydantic_xml.element(tag='name', default=None)
	target: typing.Optional[_target] = pydantic_xml.element(tag='target', default=None)

_usage = usage

class secret(pydantic_xml.BaseXmlModel, tag='secret', search_mode='unordered'):
	ephemeral: typing.Optional[typing.Literal['yes', 'no']] = pydantic_xml.attr(name='ephemeral', default=None)
	private: typing.Optional[typing.Literal['yes', 'no']] = pydantic_xml.attr(name='private', default=None)
	uuid: typing.Optional[_uuid] = pydantic_xml.element(tag='uuid', default=None)
	description: typing.Optional[_description] = pydantic_xml.element(tag='description', default=None)
	usage: typing.Optional[_usage] = pydantic_xml.element(tag='usage', default=None)

_secret = secret

secret = _secret

