import typing
import pydantic
import pydantic_xml

# This file was automatically generated by relaxng-to-pydantic. Do not modify.
class name(pydantic_xml.BaseXmlModel, tag='name', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='[^/]+')]

_name = name

class key(pydantic_xml.BaseXmlModel, tag='key', search_mode='strict'):
	value: str

_key = key

class extent(pydantic_xml.BaseXmlModel, tag='extent', search_mode='strict'):
	start: int = pydantic_xml.attr(name='start')
	end: int = pydantic_xml.attr(name='end')

_extent = extent

class sourcedev(pydantic_xml.BaseXmlModel, tag='device', search_mode='unordered'):
	path: typing.Annotated[str, pydantic.Field(pattern='(/|[a-zA-Z]:\\\\).+')] = pydantic_xml.attr(name='path')
	extent_list: typing.Optional[typing.List[_extent]] = pydantic_xml.element(tag='extent', default=None)

_sourcedev = sourcedev

class source(pydantic_xml.BaseXmlModel, tag='source', search_mode='unordered'):
	device_list: typing.Optional[typing.List[_sourcedev]] = pydantic_xml.element(tag='device', default=None)

_source = source

class capacity(pydantic_xml.BaseXmlModel, tag='capacity', search_mode='strict'):
	value: int
	unit: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='([bB]([yY][tT][eE][sS]?)?)|([kKmMgGtTpPeE]([iI]?[bB])?)')]] = pydantic_xml.attr(name='unit', default=None)

_capacity = capacity

class allocation(pydantic_xml.BaseXmlModel, tag='allocation', search_mode='strict'):
	value: int
	unit: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='([bB]([yY][tT][eE][sS]?)?)|([kKmMgGtTpPeE]([iI]?[bB])?)')]] = pydantic_xml.attr(name='unit', default=None)

_allocation = allocation

class physical(pydantic_xml.BaseXmlModel, tag='physical', search_mode='strict'):
	value: int
	unit: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='([bB]([yY][tT][eE][sS]?)?)|([kKmMgGtTpPeE]([iI]?[bB])?)')]] = pydantic_xml.attr(name='unit', default=None)

_physical = physical

class target_path(pydantic_xml.BaseXmlModel, tag='path', search_mode='unordered'):
	value: typing.Union[str, typing.Annotated[str, pydantic.Field(pattern='(/|[a-zA-Z]:\\\\).+')]]

_target_path = target_path

class format(pydantic_xml.BaseXmlModel, tag='format', search_mode='strict'):
	type: typing.Literal['unknown', 'raw', 'dir', 'bochs', 'cloop', 'dmg', 'iso', 'vpc', 'vdi', 'fat', 'vhd', 'ploop', 'luks', 'cow', 'qcow', 'qcow2', 'qed', 'vmdk', 'none', 'auto', 'ext2', 'ext3', 'ext4', 'ufs', 'iso9660', 'udf', 'gfs', 'gfs2', 'vfat', 'hfs+', 'xfs', 'ocfs2', 'vmfs', 'linux', 'fat16', 'fat32', 'linux-swap', 'linux-lvm', 'linux-raid', 'extended'] = pydantic_xml.attr(name='type')

_format = format

class mode(pydantic_xml.BaseXmlModel, tag='mode', search_mode='strict'):
	value: int

_mode = mode

class owner(pydantic_xml.BaseXmlModel, tag='owner', search_mode='unordered'):
	value: typing.Union[int, typing.Literal['-1']]

_owner = owner

class group(pydantic_xml.BaseXmlModel, tag='group', search_mode='unordered'):
	value: typing.Union[int, typing.Literal['-1']]

_group = group

class label(pydantic_xml.BaseXmlModel, tag='label', search_mode='strict'):
	value: str

_label = label

class permissions(pydantic_xml.BaseXmlModel, tag='permissions', search_mode='unordered'):
	mode: typing.Optional[_mode] = pydantic_xml.element(tag='mode', default=None)
	owner: typing.Optional[_owner] = pydantic_xml.element(tag='owner', default=None)
	group: typing.Optional[_group] = pydantic_xml.element(tag='group', default=None)
	label: typing.Optional[_label] = pydantic_xml.element(tag='label', default=None)

_permissions = permissions

class atime(pydantic_xml.BaseXmlModel, tag='atime', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='[0-9]+(\\.[0-9]{0,9})?')]

_atime = atime

class btime(pydantic_xml.BaseXmlModel, tag='btime', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='[0-9]+(\\.[0-9]{0,9})?')]

_btime = btime

class ctime(pydantic_xml.BaseXmlModel, tag='ctime', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='[0-9]+(\\.[0-9]{0,9})?')]

_ctime = ctime

class mtime(pydantic_xml.BaseXmlModel, tag='mtime', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='[0-9]+(\\.[0-9]{0,9})?')]

_mtime = mtime

class timestamps(pydantic_xml.BaseXmlModel, tag='timestamps', search_mode='unordered'):
	atime: typing.Optional[_atime] = pydantic_xml.element(tag='atime', default=None)
	btime: typing.Optional[_btime] = pydantic_xml.element(tag='btime', default=None)
	ctime: typing.Optional[_ctime] = pydantic_xml.element(tag='ctime', default=None)
	mtime: typing.Optional[_mtime] = pydantic_xml.element(tag='mtime', default=None)

_timestamps = timestamps

class secret(pydantic_xml.BaseXmlModel, tag='secret', search_mode='unordered'):
	type: typing.Literal['passphrase'] = pydantic_xml.attr(name='type')
	uuid: typing.Optional[typing.Union[typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{32}')], typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{8}\\-([a-fA-F0-9]{4}\\-){3}[a-fA-F0-9]{12}')]]] = pydantic_xml.attr(name='uuid', default=None)
	usage: typing.Optional[str] = pydantic_xml.attr(name='usage', default=None)

_secret = secret

class cipher(pydantic_xml.BaseXmlModel, tag='cipher', search_mode='strict'):
	name: str = pydantic_xml.attr(name='name')
	size: int = pydantic_xml.attr(name='size')
	mode: typing.Optional[str] = pydantic_xml.attr(name='mode', default=None)
	hash: typing.Optional[str] = pydantic_xml.attr(name='hash', default=None)

_cipher = cipher

class ivgen(pydantic_xml.BaseXmlModel, tag='ivgen', search_mode='strict'):
	name: str = pydantic_xml.attr(name='name')
	hash: typing.Optional[str] = pydantic_xml.attr(name='hash', default=None)

_ivgen = ivgen

class encryption(pydantic_xml.BaseXmlModel, tag='encryption', search_mode='unordered'):
	format: typing.Literal['default', 'qcow', 'luks', 'luks2', 'luks-any'] = pydantic_xml.attr(name='format')
	engine: typing.Optional[typing.Literal['qemu', 'librbd']] = pydantic_xml.attr(name='engine', default=None)
	secret_list: typing.Optional[typing.List[_secret]] = pydantic_xml.element(tag='secret', min_length=1, default=None)
	cipher: typing.Optional[_cipher] = pydantic_xml.element(tag='cipher', default=None)
	ivgen: typing.Optional[_ivgen] = pydantic_xml.element(tag='ivgen', default=None)

_encryption = encryption

class compat(pydantic_xml.BaseXmlModel, tag='compat', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='[0-9]+\\.[0-9]+')]

_compat = compat

class nocow(pydantic_xml.BaseXmlModel, tag='nocow', search_mode='strict'):
	pass

_nocow = nocow

class cluster_size(pydantic_xml.BaseXmlModel, tag='clusterSize', search_mode='strict'):
	value: int
	unit: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='([bB]([yY][tT][eE][sS]?)?)|([kKmMgGtTpPeE]([iI]?[bB])?)')]] = pydantic_xml.attr(name='unit', default=None)

_cluster_size = cluster_size

class lazy_refcounts(pydantic_xml.BaseXmlModel, tag='lazy_refcounts', search_mode='strict'):
	pass

_lazy_refcounts = lazy_refcounts

class extended_l2(pydantic_xml.BaseXmlModel, tag='extended_l2', search_mode='strict'):
	pass

_extended_l2 = extended_l2

class file_format_features(pydantic_xml.BaseXmlModel, tag='features', search_mode='unordered'):
	lazy_refcounts: typing.Optional[_lazy_refcounts] = pydantic_xml.element(tag='lazy_refcounts', default=None)
	extended_l2: typing.Optional[_extended_l2] = pydantic_xml.element(tag='extended_l2', default=None)

_file_format_features = file_format_features

class target(pydantic_xml.BaseXmlModel, tag='target', search_mode='unordered'):
	path: typing.Optional[_target_path] = pydantic_xml.element(tag='path', default=None)
	format: typing.Optional[_format] = pydantic_xml.element(tag='format', default=None)
	permissions: typing.Optional[_permissions] = pydantic_xml.element(tag='permissions', default=None)
	timestamps: typing.Optional[_timestamps] = pydantic_xml.element(tag='timestamps', default=None)
	encryption: typing.Optional[_encryption] = pydantic_xml.element(tag='encryption', default=None)
	compat: typing.Optional[_compat] = pydantic_xml.element(tag='compat', default=None)
	nocow: typing.Optional[_nocow] = pydantic_xml.element(tag='nocow', default=None)
	cluster_size: typing.Optional[_cluster_size] = pydantic_xml.element(tag='clusterSize', default=None)
	features: typing.Optional[_file_format_features] = pydantic_xml.element(tag='features', default=None)

_target = target

class backing_store_path(pydantic_xml.BaseXmlModel, tag='path', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='(/|[a-zA-Z]:\\\\).+')]

_backing_store_path = backing_store_path

class backing_store(pydantic_xml.BaseXmlModel, tag='backingStore', search_mode='unordered'):
	path: _backing_store_path = pydantic_xml.element(tag='path')
	format: typing.Optional[_format] = pydantic_xml.element(tag='format', default=None)
	permissions: typing.Optional[_permissions] = pydantic_xml.element(tag='permissions', default=None)
	timestamps: typing.Optional[_timestamps] = pydantic_xml.element(tag='timestamps', default=None)

_backing_store = backing_store

class vol(pydantic_xml.BaseXmlModel, tag='volume', search_mode='unordered'):
	type: typing.Optional[typing.Literal['file', 'block', 'dir', 'network', 'netdir']] = pydantic_xml.attr(name='type', default=None)
	name: _name = pydantic_xml.element(tag='name')
	key: typing.Optional[_key] = pydantic_xml.element(tag='key', default=None)
	source: typing.Optional[_source] = pydantic_xml.element(tag='source', default=None)
	capacity: typing.Optional[_capacity] = pydantic_xml.element(tag='capacity', default=None)
	allocation: typing.Optional[_allocation] = pydantic_xml.element(tag='allocation', default=None)
	physical: typing.Optional[_physical] = pydantic_xml.element(tag='physical', default=None)
	target: _target = pydantic_xml.element(tag='target')
	backing_store: typing.Optional[_backing_store] = pydantic_xml.element(tag='backingStore', default=None)

_vol = vol

storagevol = _vol

