import typing
import pydantic
import pydantic_xml

# This file was automatically generated by relaxng-to-pydantic. Do not modify.
class name(pydantic_xml.BaseXmlModel, tag='name', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='[^/\\n]+')]

_name = name

class uuid(pydantic_xml.BaseXmlModel, tag='uuid', search_mode='unordered'):
	value: typing.Union[typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{32}')], typing.Annotated[str, pydantic.Field(pattern='[a-fA-F0-9]{8}\\-([a-fA-F0-9]{4}\\-){3}[a-fA-F0-9]{12}')]]

_uuid = uuid

class capacity(pydantic_xml.BaseXmlModel, tag='capacity', search_mode='strict'):
	value: int
	unit: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='([bB]([yY][tT][eE][sS]?)?)|([kKmMgGtTpPeE]([iI]?[bB])?)')]] = pydantic_xml.attr(name='unit', default=None)

_capacity = capacity

class allocation(pydantic_xml.BaseXmlModel, tag='allocation', search_mode='strict'):
	value: int
	unit: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='([bB]([yY][tT][eE][sS]?)?)|([kKmMgGtTpPeE]([iI]?[bB])?)')]] = pydantic_xml.attr(name='unit', default=None)

_allocation = allocation

class available(pydantic_xml.BaseXmlModel, tag='available', search_mode='strict'):
	value: int
	unit: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='([bB]([yY][tT][eE][sS]?)?)|([kKmMgGtTpPeE]([iI]?[bB])?)')]] = pydantic_xml.attr(name='unit', default=None)

_available = available

class cow(pydantic_xml.BaseXmlModel, tag='cow', search_mode='strict'):
	state: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='state')

_cow = cow

class features(pydantic_xml.BaseXmlModel, tag='features', search_mode='unordered'):
	cow: typing.Optional[_cow] = pydantic_xml.element(tag='cow', default=None)

_features = features

class vendor(pydantic_xml.BaseXmlModel, tag='vendor', search_mode='strict'):
	name: str = pydantic_xml.attr(name='name')

_vendor = vendor

class product(pydantic_xml.BaseXmlModel, tag='product', search_mode='strict'):
	name: str = pydantic_xml.attr(name='name')

_product = product

class path(pydantic_xml.BaseXmlModel, tag='path', search_mode='strict'):
	value: typing.Annotated[str, pydantic.Field(pattern='(/|[a-zA-Z]:\\\\).+')]

_path = path

class mode(pydantic_xml.BaseXmlModel, tag='mode', search_mode='strict'):
	value: int

_mode = mode

class owner(pydantic_xml.BaseXmlModel, tag='owner', search_mode='unordered'):
	value: typing.Union[int, typing.Literal['-1']]

_owner = owner

class group(pydantic_xml.BaseXmlModel, tag='group', search_mode='unordered'):
	value: typing.Union[int, typing.Literal['-1']]

_group = group

class label(pydantic_xml.BaseXmlModel, tag='label', search_mode='strict'):
	value: str

_label = label

class permissions(pydantic_xml.BaseXmlModel, tag='permissions', search_mode='unordered'):
	mode: typing.Optional[_mode] = pydantic_xml.element(tag='mode', default=None)
	owner: typing.Optional[_owner] = pydantic_xml.element(tag='owner', default=None)
	group: typing.Optional[_group] = pydantic_xml.element(tag='group', default=None)
	label: typing.Optional[_label] = pydantic_xml.element(tag='label', default=None)

_permissions = permissions

class free_extent(pydantic_xml.BaseXmlModel, tag='freeExtent', search_mode='strict'):
	start: int = pydantic_xml.attr(name='start')
	end: int = pydantic_xml.attr(name='end')

_free_extent = free_extent

class sourceinfodev(pydantic_xml.BaseXmlModel, tag='device', search_mode='unordered'):
	model_config = {'extra': 'forbid'}
	path: typing.Union[typing.Annotated[str, pydantic.Field(pattern='(/|[a-zA-Z]:\\\\).+')], typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9_\\+\\-]+')], typing.Annotated[str, pydantic.Field(pattern='iqn\\.[0-9]{4}-(0[1-9]|1[0-2])\\.[a-zA-Z0-9\\.\\-]+(:.+)?')]] = pydantic_xml.attr(name='path')
	free_extent_list: typing.Optional[typing.List[_free_extent]] = pydantic_xml.element(tag='freeExtent', default=None)
	part_separator: typing.Optional[typing.Literal['yes', 'no']] = pydantic_xml.attr(name='part_separator', default=None)

_sourceinfodev = sourceinfodev

class fs_mount_opts_option(pydantic_xml.BaseXmlModel, tag='option', ns='fs', nsmap={'fs': 'http://libvirt.org/schemas/storagepool/fs/1.0'}, search_mode='strict'):
	name: str = pydantic_xml.attr(name='name')

_fs_mount_opts_option = fs_mount_opts_option

class fs_mount_opts(pydantic_xml.BaseXmlModel, tag='mount_opts', ns='fs', nsmap={'fs': 'http://libvirt.org/schemas/storagepool/fs/1.0'}, search_mode='unordered'):
	option_list: typing.Optional[typing.List[_fs_mount_opts_option]] = pydantic_xml.element(tag='option', default=None)

_fs_mount_opts = fs_mount_opts

class host(pydantic_xml.BaseXmlModel, tag='host', search_mode='strict'):
	name: typing.Union[typing.Annotated[str, pydantic.Field(pattern='[a-zA-Z0-9\\.\\-]+')], typing.Union[typing.Annotated[str, pydantic.Field(pattern='(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))')], typing.Annotated[str, pydantic.Field(pattern='(([0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){6}:[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){5}:([0-9A-Fa-f]{1,4}:)?[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){4}:([0-9A-Fa-f]{1,4}:){0,2}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){3}:([0-9A-Fa-f]{1,4}:){0,3}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){2}:([0-9A-Fa-f]{1,4}:){0,4}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){6}(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|(([0-9A-Fa-f]{1,4}:){0,5}:(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|(::([0-9A-Fa-f]{1,4}:){0,5}(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([1-9][0-9])|([0-9])))|([0-9A-Fa-f]{1,4}::([0-9A-Fa-f]{1,4}:){0,5}[0-9A-Fa-f]{1,4})|(::([0-9A-Fa-f]{1,4}:){0,6}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){1,7}:)|(::)')]]] = pydantic_xml.attr(name='name')
	port: typing.Optional[int] = pydantic_xml.attr(name='port', default=None)

_host = host

class protocol(pydantic_xml.BaseXmlModel, tag='protocol', search_mode='strict'):
	ver: str = pydantic_xml.attr(name='ver')

_protocol = protocol

class sourceinfoname(pydantic_xml.BaseXmlModel, tag='name', search_mode='strict'):
	model_config = {'extra': 'forbid'}
	value: str

_sourceinfoname = sourceinfoname

class targetlogical(pydantic_xml.BaseXmlModel, tag='target', search_mode='unordered'):
	path: typing.Optional[_path] = pydantic_xml.element(tag='path', default=None)
	permissions: typing.Optional[_permissions] = pydantic_xml.element(tag='permissions', default=None)

_targetlogical = targetlogical

class iqn(pydantic_xml.BaseXmlModel, tag='iqn', search_mode='strict'):
	name: str = pydantic_xml.attr(name='name')

_iqn = iqn

class initiatorinfo(pydantic_xml.BaseXmlModel, tag='initiator', search_mode='strict'):
	iqn: _iqn = pydantic_xml.element(tag='iqn')

_initiatorinfo = initiatorinfo

class sourceinfoauthsecret(pydantic_xml.BaseXmlModel, tag='secret', search_mode='unordered'):
	uuid: typing.Optional[str] = pydantic_xml.attr(name='uuid', default=None)
	usage: typing.Optional[str] = pydantic_xml.attr(name='usage', default=None)

_sourceinfoauthsecret = sourceinfoauthsecret

class sourceinfoauth(pydantic_xml.BaseXmlModel, tag='auth', search_mode='strict'):
	type: typing.Literal['chap', 'ceph'] = pydantic_xml.attr(name='type')
	username: str = pydantic_xml.attr(name='username')
	secret: _sourceinfoauthsecret = pydantic_xml.element(tag='secret')

_sourceinfoauth = sourceinfoauth

class sourceinfodeviscsidirect(pydantic_xml.BaseXmlModel, tag='device', search_mode='strict'):
	model_config = {'extra': 'forbid'}
	path: typing.Annotated[str, pydantic.Field(pattern='iqn\\.[0-9]{4}-(0[1-9]|1[0-2])\\.[a-zA-Z0-9\\.\\-]+(:.+)?')] = pydantic_xml.attr(name='path')

_sourceinfodeviscsidirect = sourceinfodeviscsidirect

class address(pydantic_xml.BaseXmlModel, tag='address', search_mode='strict'):
	domain: typing.Optional[typing.Annotated[int, pydantic.BeforeValidator(lambda v: (int(v) if v.isdigit() else int(v, 16)) if isinstance(v, str) else v)]] = pydantic_xml.attr(name='domain', default=None)
	bus: typing.Optional[typing.Annotated[int, pydantic.BeforeValidator(lambda v: (int(v) if v.isdigit() else int(v, 16)) if isinstance(v, str) else v)]] = pydantic_xml.attr(name='bus', default=None)
	slot: typing.Optional[typing.Annotated[int, pydantic.BeforeValidator(lambda v: (int(v) if v.isdigit() else int(v, 16)) if isinstance(v, str) else v)]] = pydantic_xml.attr(name='slot', default=None)
	function: typing.Optional[typing.Annotated[int, pydantic.BeforeValidator(lambda v: (int(v) if v.isdigit() else int(v, 16)) if isinstance(v, str) else v)]] = pydantic_xml.attr(name='function', default=None)
	multifunction: typing.Optional[typing.Literal['on', 'off']] = pydantic_xml.attr(name='multifunction', default=None)

_address = address

class parentaddr(pydantic_xml.BaseXmlModel, tag='parentaddr', search_mode='strict'):
	unique_id: typing.Optional[int] = pydantic_xml.attr(name='unique_id', default=None)
	address: _address = pydantic_xml.element(tag='address')

_parentaddr = parentaddr

class sourceinfoadapter(pydantic_xml.BaseXmlModel, tag='adapter', search_mode='unordered'):
	type: typing.Optional[typing.Literal['scsi_host', 'fc_host']] = pydantic_xml.attr(name='type', default=None)
	name: typing.Optional[str] = pydantic_xml.attr(name='name', default=None)
	parentaddr: typing.Optional[_parentaddr] = pydantic_xml.element(tag='parentaddr', default=None)
	parent: typing.Optional[str] = pydantic_xml.attr(name='parent', default=None)
	managed: typing.Optional[typing.Literal['yes', 'no']] = pydantic_xml.attr(name='managed', default=None)
	parent_wwnn: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='(0x)?[0-9a-fA-F]{16}')]] = pydantic_xml.attr(name='parent_wwnn', default=None)
	parent_wwpn: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='(0x)?[0-9a-fA-F]{16}')]] = pydantic_xml.attr(name='parent_wwpn', default=None)
	parent_fabric_wwn: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='(0x)?[0-9a-fA-F]{16}')]] = pydantic_xml.attr(name='parent_fabric_wwn', default=None)
	wwnn: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='(0x)?[0-9a-fA-F]{16}')]] = pydantic_xml.attr(name='wwnn', default=None)
	wwpn: typing.Optional[typing.Annotated[str, pydantic.Field(pattern='(0x)?[0-9a-fA-F]{16}')]] = pydantic_xml.attr(name='wwpn', default=None)

_sourceinfoadapter = sourceinfoadapter

class volume(pydantic_xml.BaseXmlModel, tag='volume', search_mode='strict'):
	allocation: typing.Optional[typing.Literal['default', 'capacity']] = pydantic_xml.attr(name='allocation', default=None)

_volume = volume

class refresh(pydantic_xml.BaseXmlModel, tag='refresh', search_mode='unordered'):
	volume: typing.Optional[_volume] = pydantic_xml.element(tag='volume', default=None)

_refresh = refresh

class rbd_config_opts_option(pydantic_xml.BaseXmlModel, tag='option', ns='rbd', nsmap={'rbd': 'http://libvirt.org/schemas/storagepool/rbd/1.0'}, search_mode='strict'):
	name: str = pydantic_xml.attr(name='name')
	value: str = pydantic_xml.attr(name='value')

_rbd_config_opts_option = rbd_config_opts_option

class rbd_config_opts(pydantic_xml.BaseXmlModel, tag='config_opts', ns='rbd', nsmap={'rbd': 'http://libvirt.org/schemas/storagepool/rbd/1.0'}, search_mode='unordered'):
	option_list: typing.Optional[typing.List[_rbd_config_opts_option]] = pydantic_xml.element(tag='option', default=None)

_rbd_config_opts = rbd_config_opts

class pool_format(pydantic_xml.BaseXmlModel, tag='format', search_mode='unordered'):
	type: typing.Literal['auto', 'ext2', 'ext3', 'ext4', 'ufs', 'iso9660', 'udf', 'gfs', 'gfs2', 'vfat', 'hfs+', 'xfs', 'ocfs2', 'vmfs', 'nfs', 'cifs', 'glusterfs', 'unknown', 'lvm2', 'dos', 'dvh', 'gpt', 'mac', 'bsd', 'pc98', 'sun'] = pydantic_xml.attr(name='type')
	vendor: typing.Optional[_vendor] = pydantic_xml.element(tag='vendor', default=None)
	product: typing.Optional[_product] = pydantic_xml.element(tag='product', default=None)

_pool_format = pool_format

class pool_dir(pydantic_xml.BaseXmlModel, tag='dir', search_mode='unordered'):
	path: typing.Union[typing.Union[typing.Annotated[str, pydantic.Field(pattern='/.*')], typing.Annotated[str, pydantic.Field(pattern='.+')]], typing.Annotated[str, pydantic.Field(pattern='/.*')]] = pydantic_xml.attr(name='path')

_pool_dir = pool_dir

class pool_source(pydantic_xml.BaseXmlModel, tag='source', search_mode='unordered'):
	vendor: typing.Optional[_vendor] = pydantic_xml.element(tag='vendor', default=None)
	product: typing.Optional[_product] = pydantic_xml.element(tag='product', default=None)
	device: typing.Optional[typing.List[typing.Union[_sourceinfodev, _sourceinfodev, _sourceinfodeviscsidirect]]] = pydantic_xml.element(tag='device', default=None)
	format: typing.Optional[_pool_format] = pydantic_xml.element(tag='format', default=None)
	host_list: typing.Optional[typing.List[_host]] = pydantic_xml.element(tag='host', default=None)
	dir: typing.Optional[_pool_dir] = pydantic_xml.element(tag='dir', default=None)
	protocol: typing.Optional[_protocol] = pydantic_xml.element(tag='protocol', default=None)
	name_list: typing.Optional[typing.List[typing.Union[_sourceinfoname, _sourceinfoname]]] = pydantic_xml.element(tag='name', default=None)
	initiator: typing.Optional[_initiatorinfo] = pydantic_xml.element(tag='initiator', default=None)
	auth: typing.Optional[_sourceinfoauth] = pydantic_xml.element(tag='auth', default=None)
	adapter: typing.Optional[_sourceinfoadapter] = pydantic_xml.element(tag='adapter', default=None)

_pool_source = pool_source

class pool(pydantic_xml.BaseXmlModel, tag='pool', search_mode='unordered'):
	type: typing.Literal['dir', 'fs', 'netfs', 'logical', 'disk', 'iscsi', 'iscsi-direct', 'scsi', 'mpath', 'rbd', 'sheepdog', 'gluster', 'zfs', 'vstorage'] = pydantic_xml.attr(name='type')
	name: typing.Optional[_name] = pydantic_xml.element(tag='name', default=None)
	uuid: typing.Optional[_uuid] = pydantic_xml.element(tag='uuid', default=None)
	capacity: typing.Optional[_capacity] = pydantic_xml.element(tag='capacity', default=None)
	allocation: typing.Optional[_allocation] = pydantic_xml.element(tag='allocation', default=None)
	available: typing.Optional[_available] = pydantic_xml.element(tag='available', default=None)
	features: typing.Optional[_features] = pydantic_xml.element(tag='features', default=None)
	source: typing.Optional[_pool_source] = pydantic_xml.element(tag='source', default=None)
	target: typing.Optional[_targetlogical] = pydantic_xml.element(tag='target', default=None)
	fs_mount_opts: typing.Optional[_fs_mount_opts] = pydantic_xml.element(tag='mount_opts', default=None)
	refresh: typing.Optional[_refresh] = pydantic_xml.element(tag='refresh', default=None)
	rbd_config_opts: typing.Optional[_rbd_config_opts] = pydantic_xml.element(tag='config_opts', default=None)

_pool = pool

storagepool = _pool

