import typing
import pydantic
import pydantic_xml

# This file was automatically generated by relaxng-to-pydantic. Do not modify.
class pool_default_format(pydantic_xml.BaseXmlModel, tag='defaultFormat', search_mode='strict'):
	type: str = pydantic_xml.attr(name='type')

_pool_default_format = pool_default_format

class value(pydantic_xml.BaseXmlModel, tag='value', search_mode='strict'):
	value: str

_value = value

class enum(pydantic_xml.BaseXmlModel, tag='enum', search_mode='unordered'):
	name: str = pydantic_xml.attr(name='name')
	value_list: typing.Optional[typing.List[_value]] = pydantic_xml.element(tag='value', default=None)

_enum = enum

class pool_caps_pool_options(pydantic_xml.BaseXmlModel, tag='poolOptions', search_mode='unordered'):
	default_format: typing.Optional[_pool_default_format] = pydantic_xml.element(tag='defaultFormat', default=None)
	enum_list: typing.Optional[typing.List[_enum]] = pydantic_xml.element(tag='enum', default=None)

_pool_caps_pool_options = pool_caps_pool_options

class pool_caps_vol_options(pydantic_xml.BaseXmlModel, tag='volOptions', search_mode='unordered'):
	default_format: _pool_default_format = pydantic_xml.element(tag='defaultFormat')
	enum_list: typing.Optional[typing.List[_enum]] = pydantic_xml.element(tag='enum', default=None)

_pool_caps_vol_options = pool_caps_vol_options

class pool_caps_type(pydantic_xml.BaseXmlModel, tag='pool', search_mode='strict'):
	type: str = pydantic_xml.attr(name='type')
	supported: typing.Literal['yes', 'no'] = pydantic_xml.attr(name='supported')
	pool_options: typing.Optional[_pool_caps_pool_options] = pydantic_xml.element(tag='poolOptions', default=None)
	vol_options: typing.Optional[_pool_caps_vol_options] = pydantic_xml.element(tag='volOptions', default=None)

_pool_caps_type = pool_caps_type

class storagepool_capabilities(pydantic_xml.BaseXmlModel, tag='storagepoolCapabilities', search_mode='unordered'):
	pool_list: typing.Optional[typing.List[_pool_caps_type]] = pydantic_xml.element(tag='pool', default=None)

_storagepool_capabilities = storagepool_capabilities

storagepoolcaps = _storagepool_capabilities

