import typing
import pydantic
import pydantic_xml

# This file was automatically generated by relaxng-to-pydantic. Do not modify.
class bios_entry(pydantic_xml.BaseXmlModel, tag='entry', search_mode='strict'):
	value: str
	name: typing.Literal['vendor', 'version', 'date', 'release'] = pydantic_xml.attr(name='name')

_bios_entry = bios_entry

class bios(pydantic_xml.BaseXmlModel, tag='bios', search_mode='unordered'):
	entry_list: typing.List[_bios_entry] = pydantic_xml.element(tag='entry', min_length=1)

_bios = bios

class system_entry(pydantic_xml.BaseXmlModel, tag='entry', search_mode='strict'):
	value: str
	name: typing.Literal['manufacturer', 'product', 'version', 'serial', 'uuid', 'sku', 'family'] = pydantic_xml.attr(name='name')

_system_entry = system_entry

class system(pydantic_xml.BaseXmlModel, tag='system', search_mode='unordered'):
	entry_list: typing.List[_system_entry] = pydantic_xml.element(tag='entry', min_length=1)

_system = system

class base_board_entry(pydantic_xml.BaseXmlModel, tag='entry', search_mode='strict'):
	value: str
	name: typing.Literal['manufacturer', 'product', 'version', 'serial', 'asset', 'location'] = pydantic_xml.attr(name='name')

_base_board_entry = base_board_entry

class base_board(pydantic_xml.BaseXmlModel, tag='baseBoard', search_mode='unordered'):
	entry_list: typing.List[_base_board_entry] = pydantic_xml.element(tag='entry', min_length=1)

_base_board = base_board

class processor_entry(pydantic_xml.BaseXmlModel, tag='entry', search_mode='strict'):
	value: str
	name: typing.Literal['socket_destination', 'type', 'family', 'manufacturer', 'signature', 'version', 'external_clock', 'max_speed', 'status', 'serial_number', 'part_number'] = pydantic_xml.attr(name='name')

_processor_entry = processor_entry

class processor(pydantic_xml.BaseXmlModel, tag='processor', search_mode='unordered'):
	entry_list: typing.List[_processor_entry] = pydantic_xml.element(tag='entry', min_length=1)

_processor = processor

class memory_device_entry(pydantic_xml.BaseXmlModel, tag='entry', search_mode='strict'):
	value: str
	name: typing.Literal['size', 'form_factor', 'locator', 'bank_locator', 'type', 'type_detail', 'speed', 'manufacturer', 'serial_number', 'part_number'] = pydantic_xml.attr(name='name')

_memory_device_entry = memory_device_entry

class memory_device(pydantic_xml.BaseXmlModel, tag='memory_device', search_mode='unordered'):
	entry_list: typing.List[_memory_device_entry] = pydantic_xml.element(tag='entry', min_length=1)

_memory_device = memory_device

class chassis_entry(pydantic_xml.BaseXmlModel, tag='entry', search_mode='strict'):
	value: str
	name: typing.Literal['manufacturer', 'version', 'serial', 'asset', 'sku'] = pydantic_xml.attr(name='name')

_chassis_entry = chassis_entry

class chassis(pydantic_xml.BaseXmlModel, tag='chassis', search_mode='unordered'):
	entry_list: typing.List[_chassis_entry] = pydantic_xml.element(tag='entry', min_length=1)

_chassis = chassis

class oem_strings_entry(pydantic_xml.BaseXmlModel, tag='entry', search_mode='strict'):
	value: str

_oem_strings_entry = oem_strings_entry

class oem_strings(pydantic_xml.BaseXmlModel, tag='oemStrings', search_mode='unordered'):
	entry_list: typing.List[_oem_strings_entry] = pydantic_xml.element(tag='entry', min_length=1)

_oem_strings = oem_strings

class sysinfo_fwcfg_entry(pydantic_xml.BaseXmlModel, tag='entry', search_mode='unordered'):
	value: typing.Optional[str] = None
	name: str = pydantic_xml.attr(name='name')
	file: typing.Optional[str] = pydantic_xml.attr(name='file', default=None)

_sysinfo_fwcfg_entry = sysinfo_fwcfg_entry

class sysinfo(pydantic_xml.BaseXmlModel, tag='sysinfo', search_mode='unordered'):
	type: typing.Literal['smbios', 'fwcfg'] = pydantic_xml.attr(name='type')
	bios: typing.Optional[_bios] = pydantic_xml.element(tag='bios', default=None)
	system: typing.Optional[_system] = pydantic_xml.element(tag='system', default=None)
	base_board_list: typing.Optional[typing.List[_base_board]] = pydantic_xml.element(tag='baseBoard', default=None)
	processor_list: typing.Optional[typing.List[_processor]] = pydantic_xml.element(tag='processor', default=None)
	memory_device_list: typing.Optional[typing.List[_memory_device]] = pydantic_xml.element(tag='memory_device', default=None)
	chassis: typing.Optional[_chassis] = pydantic_xml.element(tag='chassis', default=None)
	oem_strings: typing.Optional[_oem_strings] = pydantic_xml.element(tag='oemStrings', default=None)
	entry_list: typing.Optional[typing.List[_sysinfo_fwcfg_entry]] = pydantic_xml.element(tag='entry', default=None)

_sysinfo = sysinfo

sysinfo = _sysinfo

